### ISSUE TITLE
Value of web vitals Events in GA

### ISSUE THREAD

**Issue by KarnaVay** [GoogleChrome/web-vitals#103]
Hi Colleagues! 

We have implemented Core Web Vitals Tracking via GTM as recommended here  https://web.dev/vitals/#measure-core-web-vitals-in-javascript 
So with this Library https://github.com/GoogleChrome/web-vitals 

But I have some questions about the numbers we receive: 
CLS - in classic documentation should be like 0.1, 0.25,  In GA we receiving numbers like 1694, etc. 
Could you help me with clarifying - 0.1 - it will be 1000, or 100? And 0.25 will be 250 or 2500?
And I also wonder about FID - good Value, in this case, will be 100 and less, am I right?

I need it to properly separate events in GA - https://www.screencast.com/t/v1p00x9INkcW

Thanks in Advance!

**Comment by philipwalton** [comment]
> But I have some questions about the numbers we receive:
> CLS - in classic documentation should be like 0.1, 0.25, In GA we receiving numbers like 1694, etc.
> Could you help me with clarifying - 0.1 - it will be 1000, or 100? And 0.25 will be 250 or 2500?

Happy to clarify. If you read closely the code comment from the [example in the README](https://github.com/GoogleChrome/web-vitals#send-the-results-to-google-analytics), you'll see it says:

```js
// Google Analytics metrics must be integers, so the value is rounded.
// For CLS the value is first multiplied by 1000 for greater precision
// (note: increase the multiplier for greater precision if needed).
```

In other words, a CLS of 100 in GA will equal 0.1, which is the recommended "good" threshold. Similarly a CLS of 250 in GA will equal the "poor" threshold.

> And I also wonder about FID - good Value, in this case, will be 100 and less, am I right?

In the case of FID, the values are in milliseconds, so yes, a "good" value is 100 or less.
