### ISSUE TITLE
Internet Explorer 11 Support - WeakSet is undefined

### ISSUE THREAD

**Issue by cb-eli** [GoogleChrome/web-vitals#104]
Hi,

According to the README file, this library should support IE9+ without any error.
I just updated to v1.0.1 and I see that you are using WeakSet which is not supported in old browsers.

https://github.com/GoogleChrome/web-vitals/blob/bebca81aa66041ffdfacb5ae65990d1acede07f9/src/lib/finalMetrics.ts

**Comment by philipwalton** [comment]
The assumption was that folks would be using a tool like webpack or babel to compile their code and include any needed polyfills for their target environments.

Looks like enough people are being caught out by this though, so I'm happy to add #110 since it's a simple enough change.
