### ISSUE TITLE
Add a new policy called `Cumulative Scrollbar Shift (CSS)`

### ISSUE THREAD

**Issue by summercms** [GoogleChrome/web-vitals#107]
I just watched a very interesting video from Googler's Jake and Surma.

If you watch the video starting at 12:46 link here: https://youtu.be/FFA-v-CIxJQ?t=766

You will see the browser scrollbar on the right hand side `jump up` by quite a large amount.

![ezgif-7-8da8ccbb41c9](https://user-images.githubusercontent.com/57409060/102125037-f12cb480-3e40-11eb-9960-e356c458f429.gif)

This is not a good user experience and I've seen this issue from many websites using infinite scrolling.

I think a new web vitals measurement should be created to measure this scrolling jump and if the scrollbar jumps up or down by a certain percentage then it should flag the `Cumulative Scrollbar Shift (CSS)`

**Comment by philipwalton** [comment]
Thanks for the suggestion (and sorry for the slow reply, this somehow slipped my inbox).

This library is primarily concerned with providing implementations for the existing Web Vitals metrics (as documented on [web.dev/vitals](https://web.dev/vitals/)). If you want to suggest a new Web Vitals metric, I'd recommend emailing [web-vitals-feedback@googlegroups.com](mailto:web-vitals-feedback@googlegroups.com), as the people checking that list are the right people to give this suggestion to.
