### ISSUE TITLE
CLS Value Issue + Network Information

### ISSUE THREAD

**Issue by rjscoleman** [GoogleChrome/web-vitals#118]
Hello,

We are using the GTM variation of the web vitals script / library (see .txt attached) to measure the core vitals.

[webvitals.txt](https://github.com/GoogleChrome/web-vitals/files/5834937/webvitals.txt)

**1. CLS Value Issue:**
The CLS value which is pushed in the dataLayer and sent to GA is rounded so much that it is pretty much unusable (see attached some examples comparing the actual CLS value to what is sent to GA). I have tried changing the modifier in the JS to 100000 but it hasn't made a difference to what is sent to GA.

Is it possible to modify the code so that we capture a  granular / usable  CLS value in GA that allows us to know how we are comparing against the benchmarks?

![image](https://user-images.githubusercontent.com/77665439/105018943-79543a00-5a3d-11eb-9512-365cf467c893.png)
![image](https://user-images.githubusercontent.com/77665439/105019088-9ee14380-5a3d-11eb-8015-8540e1a250c1.png)

**2. Network Information**

Is it possible to update the library also please to send the networking information of the user in addition to the core web vitals?

See https://wicg.github.io/netinfo/#effective-connection-types

**Comment by philipwalton** [comment]
You can use a [custom dimension](https://support.google.com/analytics/answer/2709828?hl=en) to measure effective connection type, and I recommend measuring it as a custom dimension (instead of only measuring it for Web Vitals metrics) because then you can use it to report/analytics across any performance or business metric important to your site.

**Comment by rjscoleman** [comment]
Thanks  @philipwalton. Looking forward to your feedback on the first CLS item

**Comment by philipwalton** [comment]
Can you show me the code you're using? If following [the code outlined in the README](https://github.com/GoogleChrome/web-vitals#send-the-results-to-google-analytics), then a CLS of `0.0165` should get reported as `17`, since the CLS values are multiplied by 1000 and then rounded.

**Comment by rjscoleman** [comment]
Hi Phil,

The code is in the original post. Please see the .txt link.

We are using GTM to inject it and then setting up a separate GA tag in GTM which is triggered base on the dataLayer pushes.

Cheers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by philipwalton** [comment]
Based on the code you linked to, I can see an error. It looks like you mis-copied somehow, as you're comparing to the string `'cls'` (lowercase) instead of the correct string `'CLS'` (uppercase).

Here's the line in your code:

```js
value: Math.round(name.name === 'cls' ? name.delta * 1000 : name.delta),
```

**Comment by rjscoleman** [comment]
@philipwalton thanks very much 
![image](https://user-images.githubusercontent.com/77665439/105327628-07a7f780-5bc7-11eb-84f3-c9c4d376782c.png)
