### ISSUE TITLE
support in non-Chromium browsers

### ISSUE THREAD

**Issue by macgyver** [GoogleChrome/web-vitals#122]
Hi there, my team is interested in using this library to collect field data to flesh out the information from the Core Web Vitals report in the Google Search Console, in particular we hoped to be able to include data from browsers other than Chrome.

I've implemented reporters for CLS, LCP, and FID in my local development version of the site and I am seeing the reporting I would expect when I test in Chrome, but it seems that nothing is reported in Safari and only FID is coming through in Firefox. I don't understand why this should be, as `PerformanceObserver` is nominally supported in both those browsers. I've tried both the standard and base+polyfill version and I get the same outcome either way.

I double-checked by cloning the repo and running the test server and it does seem to confirm that only Chrome is logging these events - I tested in Chrome, Firefox, Safari, and the Safari simulator. Functioning in iOS Safari is especially important to us because it represents a significant share of our traffic.

**Comment by philipwalton** [comment]
> I've implemented reporters for CLS, LCP, and FID in my local development version of the site and I am seeing the reporting I would expect when I test in Chrome, but it seems that nothing is reported in Safari and only FID is coming through in Firefox.

FID should be reported in both Safari and Firefox, but it's expected that you wouldn't see LCP and CLS in either of these browsers.

See the [browser support](https://github.com/GoogleChrome/web-vitals#browser-support) section of the README for more details on exactly which browsers support which APIs.

> I don't understand why this should be, as `PerformanceObserver` is nominally supported in both those browsers. I've tried both the standard and base+polyfill version and I get the same outcome either way.

Yes, `PerformanceObserver` is supported in multiple browsers but what you need to check is support for the relevant entry types.

E.g. you can run this in your browser to see:

```js
console.log(PerformanceObserver.supportedEntryTypes);
```

The entry type you need for LCP is `largest-contentful-paint`, for FID it's `first-input`, and for CLS it's `layout-shift`.

The base+polyfill version of the library only polyfills the `first-input` entry, as that's the only one that can be reasonably polyfilled in a performant way.

**Comment by macgyver** [comment]
ok thanks, sorry - not sure how I missed that section. I guess I just assumed that anything claiming to be a polyfill would cover more of the features.
