### ISSUE TITLE
Do not use installTriger to detect Firefox

### ISSUE THREAD

**Issue by karlcow** [GoogleChrome/web-vitals#124]
Hi,

This code here is using [`installTrigger`](https://developer.mozilla.org/en-US/docs/Web/API/InstallTrigger) for detecting Firefox. 

https://github.com/GoogleChrome/web-vitals/blob/dd140f82df037e70f58708a4d173a50da0278b19/src/lib/onHidden.ts#L25-L35

This is a non standard API. And exposing it for something which is not related to its purpose creates future Web compability issues. If one days, Mozilla wants to remove it from Firefox (for any reasons), it will break web-vitals and other sites using it. In return it might become a case of "Mozilla needs to leave it there" because it will break too many sites.

In addition it seems it was added to avoid to trigger a bug that Chrome has in the first place. 
https://bugs.chromium.org/p/chromium/issues/detail?id=987409

This was added during this commit by @philipwalton  
https://github.com/GoogleChrome/web-vitals/commit/8fd2287c1e7353d25695a90d605d7bbaac27ff2f

That would be cool to fix that 😄  Thanks 
cc @miketaylr

**Comment by philipwalton** [comment]
I understand the issue you're describing, and I understand why it can be problematic. I this case I needed to specifically target Firefox/Gecko to avoid adding something that would negatively affect performance in Firefox, which seemed worth it to me.

I suppose I could have also used UA sniffing, but that has problems as well.

Given that the bug in question has now been fixed for more than 3 Chrome versions, I think at this point it's fine to remove the check altogether.
