### ISSUE TITLE
FID value rating

### ISSUE THREAD

**Issue by dainemawer** [GoogleChrome/web-vitals#125]
Hi everyone! Great library. I'm wondering...in the FID [documentation](https://web.dev/fid/), it's stated that a healthy FID score should be below 100ms. When tracking FID through web-vitals.js using `getFID(console.log)` - the results often return something like this: `value: 4.750000000058208` - is that value in `s` or `ms`? It's not evidently clear at this point, any clarification would be greatly appreciated.

**Comment by dainemawer** [comment]
Ah, excellent, thanks very much for the clarification @mikegeyser

**Comment by philipwalton** [comment]
Yes, @mikegeyser is correct. I've updated the README to link to the MDN docs for `DOMHighResTimeStamp`.
