### ISSUE TITLE
FID not firing if I switch tabs before interacting with the page

### ISSUE THREAD

**Issue by Tiggerito** [GoogleChrome/web-vitals#130]
If I load a page, switch to another tab, switch back, then click on the page, I don't see an FID event.

If I load the page and click I do.

**Comment by philipwalton** [comment]
Yes, this is expected. Similar to FCP and LCP, FID is only reported if the page was not backgrounded prior to the first input (for FCP and LCP, pages loaded in the background are also not counted).

You can see more details here: https://web.dev/fid/#differences-between-the-metric-and-the-api
