### ISSUE TITLE
Zero delta CLS in some Android devices

### ISSUE THREAD

**Issue by Tiggerito** [GoogleChrome/web-vitals#131]
While making reports on the web vitals data I am gathering I noticed quite a lot of zero delta values for CLS and a pages total CLS was also zero. This concerned me as those entries would pull down the average CLS.

I dug into the data and it only happens on Android 7, 9, 10 or 11 devices using Chrome,  Samsung Internet or Android viewweb. And not all the time.

Could these be true zero CLSs?

**Comment by philipwalton** [comment]
Sorry for the slow response (missed the notification for this somehow).

Are you rounding the CLS values before sending them to your analytics system? If so, then I suspect the issue is that the layout shifts are real, but they're so small they get rounded to 0.

**Comment by Tiggerito** [comment]
I don't do any rounding, but I think Google Analytics does. A bug in GA4 DebugView highlighted that fractional numbers are multiplied by 1000000 and stored as integers.

I did some playing via Data Studio and it looks like values from GA4 are rounded to the nearest 0.000001

Another check of the data and it seems these close to zero CLSs happen on all devices, so that I think was a red herring.
