### ISSUE TITLE
Is there a way to detect when web-vitals is not supported on the browser in use? 

### ISSUE THREAD

**Issue by bbehnke** [GoogleChrome/web-vitals#133]
I am having hard time finding a comprehensive list of browser support for web-vitals, especially mobile browser versions. Due to this I would like to log when the library is not supported in order to begin building a list of unsupported browsers for my team to reference.

I don't see any errors thrown or an error callback option. Is there a way to determine this in the library's current state?

**Comment by bbehnke** [comment]
@philipwalton or other contributors, has anyone solved for this use case in the past?

**Comment by philipwalton** [comment]
The library itself should run without error in all browsers, but the callbacks will only be invoked in the browser supports that support underlying API.

The [browser support](https://github.com/GoogleChrome/web-vitals#browser-support) section of the README covers exactly what browsers are supported.

**Comment by brandon-promoonly** [comment]
Also be aware that Firefox will no longer send data to Google Analytics.
https://developer.mozilla.org/en-US/docs/Web/Privacy/Tracking_Protection#what_does_this_mean_for_your_website

**Comment by philipwalton** [comment]
@brandon-promoonly this library does not require Google Analytics, so support of Google Analytics is not relevant for browser support.

**Comment by philipwalton** [comment]
I'm going to close this issue since feature detection is not something I plan to add to this library in the future. Developer who want to feature detect support for these metrics can do so in their own code and the conditionally decide whether or not to load the library.

For example, they could do something like this:

```js
if (PerformanceObserver.supportedEntryTypes.includes('largest-contentful-paint')) {
  const {getLCP} = await import('/path/to/web-vitals.js');
  getLCP(sendToAnalytics);
}
```
