### ISSUE TITLE
Negative TTFB on Firefox

### ISSUE THREAD

**Issue by jenntilton-qz** [GoogleChrome/web-vitals#137]
I'm seeing instances of negative values of getTTFB(), exclusively on Firefox, despite the [docs](https://github.com/GoogleChrome/web-vitals#browser-support) claiming that Firefox is a supported browser.

![image](https://user-images.githubusercontent.com/64432694/115437838-8a8a1f80-a1c1-11eb-8566-5f82038a500b.png)

Seems related to [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1429422).

If it helps, I found that these Navigation Timing attributes are also negative in these cases.
```
connect_end
connect_start
domain_lookup_start
fetch_start
redirect_end
redirect_start
request_start
response_end
response_start
secure_connection_start
time_to_first_byte
```

**Comment by philipwalton** [comment]
What version of the library are you using? As you might have seen from the Firefox bug you linked to, I commented in that thread that I fixed this issue in `v1.1.0`.

Based on the following code, it shouldn't be possible to report a negative number for any of those values:
https://github.com/GoogleChrome/web-vitals/blob/v1.1.0/src/getTTFB.ts#L42-L44

**Comment by kevinmoch-qz** [comment]
Same team here as the above questioner -- can confirm we are and have been on `v1.1.1`.

**Comment by philipwalton** [comment]
Update: I was looking at the data from a few sites I maintain, and I noticed the negative values as well. It looks like the issue is not the above [performance timing bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1429422), but instead a bug with Navigation Timings (as all Firefox versions with negative TTFB I checked support the newer Navigation Timing API).

<table>
  <tr>
    <td>Row</td>
    <td>TTFB</td>
    <td>browser</td>
    <td>browser_version</td>
    <td>operating_system</td>
  </tr>
  <tr>
    <td>1</td>
    <td>-3998.0</td>
    <td>Firefox</td>
    <td>87.0</td>
    <td>Android</td>
  </tr>
  <tr>
    <td>2</td>
    <td>-893.0</td>
    <td>Firefox</td>
    <td>78.0</td>
    <td>Macintosh</td>
  </tr>
  <tr>
    <td>3</td>
    <td>-258.0</td>
    <td>Firefox</td>
    <td>86.0</td>
    <td>Windows</td>
  </tr>
  <tr>
    <td>4</td>
    <td>-229.0</td>
    <td>Firefox</td>
    <td>86.0</td>
    <td>Windows</td>
  </tr>
  <tr>
    <td>5</td>
    <td>-157.0</td>
    <td>Firefox</td>
    <td>78.0</td>
    <td>Windows</td>
  </tr>
  <tr>
    <td>6</td>
    <td>-151.0</td>
    <td>Firefox</td>
    <td>87.0</td>
    <td>Linux</td>
  </tr>
  <tr>
    <td>7</td>
    <td>-147.0</td>
    <td>Firefox</td>
    <td>86.0</td>
    <td>Macintosh</td>
  </tr>
  <tr>
    <td>8</td>
    <td>-94.0</td>
    <td>Firefox</td>
    <td>86.0</td>
    <td>Linux</td>
  </tr>
  <tr>
    <td>9</td>
    <td>-88.0</td>
    <td>Firefox</td>
    <td>86.0</td>
    <td>Windows</td>
  </tr>
  <tr>
    <td>10</td>
    <td>-82.0</td>
    <td>Firefox</td>
    <td>78.0</td>
    <td>Windows</td>
  </tr>
  <tr>
    <td>11</td>
    <td>-80.0</td>
    <td>Firefox</td>
    <td>87.0</td>
    <td>Windows</td>
  </tr>
  <tr>
    <td>12</td>
    <td>-78.0</td>
    <td>Firefox</td>
    <td>87.0</td>
    <td>Android</td>
  </tr>
  <tr>
    <td>13</td>
    <td>-69.0</td>
    <td>Firefox</td>
    <td>86.0</td>
    <td>Windows</td>
  </tr>
  <tr>
    <td>14</td>
    <td>-59.0</td>
    <td>Firefox</td>
    <td>88.0</td>
    <td>Windows</td>
  </tr>
  <tr>
    <td>15</td>
    <td>-53.0</td>
    <td>Firefox</td>
    <td>87.0</td>
    <td>Macintosh</td>
  </tr>
  <tr>
    <td>16</td>
    <td>-48.0</td>
    <td>Firefox</td>
    <td>87.0</td>
    <td>Macintosh</td>
  </tr>
  <tr>
    <td>17</td>
    <td>-44.0</td>
    <td>Firefox</td>
    <td>78.0</td>
    <td>Linux</td>
  </tr>
  <tr>
    <td>18</td>
    <td>-38.0</td>
    <td>Firefox</td>
    <td>88.0</td>
    <td>Windows</td>
  </tr>
  <tr>
    <td>19</td>
    <td>-25.0</td>
    <td>Firefox</td>
    <td>85.0</td>
    <td>Windows</td>
  </tr>
  <tr>
    <td>20</td>
    <td>-14.0</td>
    <td>Firefox</td>
    <td>87.0</td>
    <td>Windows</td>
  </tr>
</table>

(Note: the total results for Firefox in this query was 3155, which means the negative results represent **0.63%**)

I'll file a bug about this with Firefox.

**Comment by kevinmoch-qz** [comment]
Appreciate this. For our part, we're filtering out the negative values for the time being.

**Comment by philipwalton** [comment]
Yes, I think it probably does make sense to just not report if the value is negative. I think I'll add that logic to the library itself.

**Comment by philipwalton** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1709427

**Comment by bradfrosty** [comment]
@nicjansma wrote a great blog post about [Navigation Timing in Practice](https://nicj.net/navigationtiming-in-practice/) several years back. It might be a bit out of date, but there's some useful context in there including a list of browser bugs (at the time) such as `responseStart` being reported prior to `navigationStart` (Ctrl-F for "Browser Bugs"). 

+1 for adding to the library. His suggestion was:

> If you’re analyzing NavigationTiming data, you should ensure that all timestamps increment according to the timeline. If not, you should probably question all of the timestamps and discard.
