### ISSUE TITLE
CLS shift after drag-and-dropping a file

### ISSUE THREAD

**Issue by mathieudubois666** [GoogleChrome/web-vitals#140]
We detect a lot of CLS issues in the field due to users drag-and-dropping image files on the page. Why a drag-and-drop event is not considered a valid user interaction? When the image is selected with the "browse" dialog or pasted from the clipboard, it does not cause a shift.

To reproduce the CLS shift on drag-and-drop events, run the following snippet and drop anything on the page.
```html
<html>
<head>
    <script>
        (function () {
            var script = document.createElement('script');
            script.src = 'https://unpkg.com/web-vitals';
            script.onload = function () {
                webVitals.getCLS(console.log, true);
            }
            document.head.appendChild(script);
        }())
    </script>
</head>

<body>
    <p id=content>Drop anything on the page to cause a CLS shift.</p>

    <script>
        document.body.ondragover = function (e) {
            e.preventDefault();
        }

        document.body.ondrop = function (e) {
            e.preventDefault();
            var content = document.getElementById("content");
            var newStuff = document.createElement("div");
            newStuff.style.height = "500px";
            document.body.insertBefore(newStuff, content);
        }
    </script>
</body>
</html>
```

**Comment by philipwalton** [comment]
Yep, I've noticed this as well on a few sites I work on, and I brought it up with the team and we filed [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1166952) to change the metric definition to ignore drag operations (in addition to clicks, keypress, etc.)

In short, once the change is released and users update to the latest version of Chrome, you can expect your field data to no longer include these shifts.
