### ISSUE TITLE
getCLS returns undefined instead of 0 when no shifts happened

### ISSUE THREAD

**Issue by thomthomgo** [GoogleChrome/web-vitals#151]
Hello team !

Bug description : My customer was following the guidelines from the README to collect vitals and send them to their analytics endpoint : https://github.com/GoogleChrome/web-vitals#send-the-results-to-google-analytics
They noticed discrepancies on CLS between their own collection and the CrUX report data. After investigation, we realised they were systematically sending CLS on page visibilityState changes as per the documentation, even when no layout shifts had happened. In this case, the value for CLS is undefined instead of 0, hence distorting the average CLS for their pages.

How to reproduce : Collect CLS on a page with no shift happening. getCLS will return undefined instead of a 0 value.

Expected result : CLS value should equal 0 when no shifts were reported.

Let me know if you need more details
Thanks !

**Comment by philipwalton** [comment]
> How to reproduce : Collect CLS on a page with no shift happening. getCLS will return undefined instead of a 0 value.

This is not true, CLS is either not reported or the reported value is 0. There is never a case where it is reported but it's value is undefined.

Can you share the code you're using to get a value of undefined? I suspect you're doing something like this, as that's the only way I can think of to get a value of undefined.

```js
// Don't do this, as `getCLS()` does not return a value.
const cls = getCLS();

console.log(cls); // Logs `undefined`
```

The `getCLS()` function does not return a value, instead it takes a callback that gets invoked with the value. Is it possible this is why you're seeing undefined?
