### ISSUE TITLE
Is it possible to report the LCP element?

### ISSUE THREAD

**Issue by davidcsally** [GoogleChrome/web-vitals#152]
Hello!

Is it possible to report the LCP element along with the timestamp? This would be useful for a few reasons:

- Measure the most common LCP element, so you can optimize this for your users
- Detect when the LCP element changes  

Would this be possible to do with `web-vitals` ? I've noticed that lighthouse and page speed insights both report the LCP element, but I have not seen a way to gather that information from real user metrics.

Thanks!

**Comment by csabapalfi** [comment]
Hi @davidcsally, see this article about how to track the largest LCP element as debug information using `web-vitals`: 

https://web.dev/debug-web-vitals-in-the-field/

**Comment by davidcsally** [comment]
Thanks @csabapalfi, this is exactly what I was looking for!

**Comment by philipwalton** [comment]
Yes, as @csabapalfi mentioned, this information is available by looking at the `.entries` property of the [`Metric`](https://github.com/GoogleChrome/web-vitals/#metric) object.
