### ISSUE TITLE
How to compute the same scores shown by Lighthouse for LCP and CLS?

### ISSUE THREAD

**Issue by igorgatis** [GoogleChrome/web-vitals#153]
Is there a way to produce the same metrics seen in Lighthouse?

**Comment by rviscomi** [comment]
Rather than trying to simulate lab data in the field, most people try to simulate field data in the lab, so I'm very curious to learn more about your use case. The lab-based Lighthouse data is just a simulation and may not reflect the way users actually experience the page.

**Comment by philipwalton** [comment]
> Is there a way to produce the same metrics seen in Lighthouse?

Can you be more specific? Do you mean metrics like Time to Interactive, Total Blocking Time, and Speed Index? If so then the answer is no, those are lab-specific metrics and we don't recommend sites try to measure those in the field (e.g. measuring them is either too difficult or performance intensive).

**Comment by igorgatis** [comment]
I was just a bit surprised that numbers I collected from my workstation using the library and using Lighthouse devtools UI didn't match. To start with, I was not sure when to call `getLCP` so I figured I should use `reportAllChanges = true`, which produces a list of results. The documentation says (https://web.dev/lcp/#when-is-largest-contentful-paint-reported):

> For analysis purposes, you should only report the most recently dispatched PerformanceEntry to your analytics service.

One of my website page has this late popup. The `getLCP` is sensed by this popup but Lighthouse is not because it stops measuring before the popup shows up. It is not clear to me when Lighthouse stops collecting data. Does it stop after `load` event?

The reason why I'd like to get closer number is simple: if I'm using the same computer and same browser, shouldn't it produce similar results for both `getLCP` and `Lighthouse`?

**Comment by csabapalfi** [comment]
@igorgatis Yes, Lighthouse waits until `load`: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/gather-runner.js#L75

**Comment by philipwalton** [comment]
> I was just a bit surprised that numbers I collected from my workstation using the library and using Lighthouse devtools UI didn't match.

The numbers are not expected to match. Every page load consists of a unique network request and unique CPU conditions, so the expectation is that every load (even from the same machine) will be slightly different.  See the [Lighthouse documentation on variability](https://github.com/GoogleChrome/lighthouse/blob/master/docs/variability.md) for more details.

> To start with, I was not sure when to call `getLCP` so I figured I should use `reportAllChanges = true`, which produces a list of results.

It doesn't matter when you call `getLCP()`, it can be before LCP happens or afterward, the reported value will be the same for any given page load. You do not need to set `reportAllChanges` to true to get the correct LCP value, using `reportAllChanges` is only important if you really need to know what the progression of LCP candidates was.

> One of my website page has this late popup. The `getLCP` is sensed by this popup but Lighthouse is not because it stops measuring before the popup shows up. It is not clear to me when Lighthouse stops collecting data. Does it stop after `load` event?

To Rick's point above, this is one of the reason to favor real-user data in the field over lab data collected by tools like Lighthouse. And it's why Google tools that provide incentives based on Core Web Vitals score (e.g. Google Search) always base those scores on field data and not lab data.

Lab data can be used as a guide when debugging (or before releasing new code to production), but it is not the ground truth. The real performance of your site is what is actually experienced by your real users.

> The reason why I'd like to get closer number is simple: if I'm using the same computer and same browser, shouldn't it produce similar results for both `getLCP` and `Lighthouse`?

For the same page load, yes the results should be the same. But running Lighthouse typically initiates another page load, and that is expected to produce a different value.

**Comment by igorgatis** [comment]
@philipwalton I was expecting some variance, but in my case it felt completely far apart because I was considering results after `load` event. Thanks for pointing that documentation. The cut off based on `load` event works perfectly for my use case.

Regarding `getLCP`, image that the page is composed of small parts the largest one triggers, say, at 2.0s. Around 10s later, a major popup shows up. AFAIU, if I call `getLCP` around time=5s, it LCP will be `2.0s` and if I call it again around time=20s, LCP will be 12.0s. Is that correct?

**Comment by rviscomi** [comment]
In this case it seems like you'd want to measure beyond load so that you more realistically capture what users are experiencing and how it's reported in tools like CrUX. It's not that the field data is wrong; Lighthouse isn't seeing the bigger picture.

**Comment by philipwalton** [comment]
> Regarding `getLCP`, image that the page is composed of small parts the largest one triggers, say, at 2.0s. Around 10s later, a major popup shows up. AFAIU, if I call `getLCP` around time=5s, it LCP will be `2.0s` and if I call it again around time=20s, LCP will be 12.0s. Is that correct?

This is not correct. If the "real" LCP candidate for the page loads at 12 seconds, then that will be the element that is reported regardless of when you call `getLCP()`.

Note that `getLCP()` doesn't return a value, instead it takes a callback that will be run once LCP has been determined. So it doesn't matter when you call `getLCP()`, what matters is when LCP actually was.

You can verify this yourself by setting up a test page with this exact scenario and trying it out.
