### ISSUE TITLE
BUG: Conflict with Magento's RequireJS

### ISSUE THREAD

**Issue by sahava** [GoogleChrome/web-vitals#156]
Hey!

A number of people have said that there are possible conflicts on sites running Magento and trying to load the `web-vitals` library.

For example, if you visit https://www.foeger.com/eu_de/ and try to load the `web-vitals` library, the `window.webVitals` namespace is never created. Magento uses RequireJS, and it *seems* like this could be the cause of the conflict.

Sorry for not being able to define the bug any better, but it does seem to be a recurring problem on sites running Magento and/or RequireJS.

**Comment by philipwalton** [comment]
Ahh, I see how the example on the docs wouldn't work if the page is using RequireJS or another AMD loader. For a site using RequireJS, you'd want to load it like this:

```js
require(['https://unpkg.com/web-vitals'], (webVitals) => {
    webVitals.getCLS(console.log);
    webVitals.getFID(console.log);
    webVitals.getLCP(console.log);
});
```

However, it probably doesn't make sense for your template to include a conditional that can load the script both ways depending on the environment.

I can see a few options to fix this:

1) Your template could load the library using a module script (e.g. either `<script type="module">`, or using dynamic `import()`). However, I seem to remember GTM not allowing any ES6, so I'm not sure if this is possible.

2) I could add another build of the library that just creates a browser global, and then your template could load that script. The URL would be something like: `https://unpkg.com/web-vitals/dist/web-vitals.iife.js`

What do you think?

**Comment by sahava** [comment]
Thanks - I think your final option (2) is the best in terms of GTM's template sandbox. The sandbox does allow ES6 but only selected things which have been transpiled into the sandbox JS (e.g. arrow functions, const/let), and there's no guarantee these features would get added in the future.

So having a "regular" JS script injection is likely the best option for custom templates. Thanks for looking into this!

Simo

**Comment by philipwalton** [comment]
I've added the "iife" script version discussed in option (2), and I've published v2 of the library, so you should be able to update your template to inject the following script URL:

https://unpkg.com/web-vitals/dist/web-vitals.iife.js

Let me know if this doesn't fix the issue for some reason.
