### ISSUE TITLE
getLCP only fires when tapping on something

### ISSUE THREAD

**Issue by Joelsz** [GoogleChrome/web-vitals#160]
Hi,

While trying to setup the web-vitals library, we noticed that the getLCP callback is only being called once the user has clicked on anything on the page. This shouldn't be the case for LCP which should be fired immediately when the LCP metric is determined.

With the `reportAllChanges` set to `true` it does work as intended, but per the docs this is not recommended.

We're using the following version: `https://unpkg.com/web-vitals/dist/web-vitals.iife.js` but it also seems to be the case with the regular /web-vitals package.

**Comment by philipwalton** [comment]
> This shouldn't be the case for LCP which should be fired immediately when the LCP metric is determined.

The `getLCP()` callback is fired immediately when the LCP metric is determined—it just so happens that in most cases that corresponds to when the user first interacts with the page. If the user hasn't interacted with the page, then the algorithm needs to keep watching to see if an even larger element is loaded. It only stops watching if the user interacts or if the page is unloaded.

For more details, see [When is largest contentful paint reported?](https://web.dev/lcp/#when-is-largest-contentful-paint-reported) from the LCP post on web.dev.

You might also be interested in a feature request to add a signal to the algorithm indicating when the browser has stop watching for new candidates: https://github.com/WICG/largest-contentful-paint/issues/43
