### ISSUE TITLE
Is the new way of measuring the CLS already implemented? 

### ISSUE THREAD

**Issue by jwd-analyst** [GoogleChrome/web-vitals#161]
Is the new way of measuring the CLS already implemented? 
https://web.dev/evolving-cls/
https://web.dev/cls-web-tooling/

**Comment by csabapalfi** [comment]
Yes, see v2 in the [changelog](https://github.com/GoogleChrome/web-vitals/blob/main/CHANGELOG.md#v200-2021-06-01)

**Comment by jwd-analyst** [comment]
Thanks! @csabapalfi
