### ISSUE TITLE
CLS metric should only be calculated at in view components

### ISSUE THREAD

**Issue by iceleo-com** [GoogleChrome/web-vitals#163]
when I work with your tool, I see it calculates the CLS metric at a component out of the viewport
I think it's useless for user experience. People only work on the components that they see on the screen

And another case:
My website is an e-commerce site, when I click on a filter rule, the items list is loaded via AJAX (it may take 0.5-1.5s to load). If the new number of items is less than the current number of items, the items list height is changed, the footer will be shifted, and your tool reports the CLS issue <= but in this case, there are no worse for user experience

**Comment by philipwalton** [comment]
> when I work with your tool, I see it calculates the CLS metric at a component out of the viewport
> I think it's useless for user experience. People only work on the components that they see on the screen

Do you have an example where you can show this happening? It shouldn't be possible.

The [Layout Instability API](https://wicg.github.io/layout-instability/) only considers shifts that occur within the viewport, so if you have an example of that not being the case, please report a bug on crbug.com.

> the items list height is changed, the footer will be shifted, and your tool reports the CLS issue <= but in this case, there are no worse for user experience

If the footer is shifting more than 500ms after the user interacts, then I'd argue it is worse for the experience. But either way, this library does not control the definition of CLS, it just aggregates and calculates the individual shifts that that are reported on the page by the [Layout Instability API](https://wicg.github.io/layout-instability/).

If you would like to provide feedback on the API itself, you can do that on the [spec repo](https://github.com/WICG/layout-instability/issues/). To provide feedback on the definition of CLS, you can email: web-vitals-feedback@googlegroups.com
