### ISSUE TITLE
Question about disconnect on input for LCP monitoring

### ISSUE THREAD

**Issue by neenhouse** [GoogleChrome/web-vitals#164]
Hi @philipwalton,

I have a question about https://github.com/GoogleChrome/web-vitals/blob/main/src/getLCP.ts#L64, why disconnect monitoring on LCP after user input?  I've seen you made this comment in [another thread](https://github.com/GoogleChrome/web-vitals/issues/100):

>  Currently LCP is only tracked until the first user interaction or the page is background or unloaded.

I get why you can't collect metrics when the page has been backgrounded as they are no longer comparative.  Does user interaction have the same impact on LCP metrics?  Just curious to hear your reasoning, I wasn't able to find the rationale anywhere.

Thanks!

Chris

**Comment by philipwalton** [comment]
From [the LCP guide](https://web.dev/lcp/#:~:text=The%20browser%20will%20stop%20reporting%20new%20entries%20as%20soon%20as%20the%20user%20interacts%20with%20the%20page%20(via%20a%20tap%2C%20scroll%2C%20or%20keypress)%2C%20as%20user%20interaction%20often%20changes%20what%27s%20visible%20to%20the%20user%20(which%20is%20especially%20true%20with%20scrolling).) on web.dev:

> The browser will stop reporting new entries as soon as the user interacts with the page (via a tap, scroll, or keypress), as user interaction often changes what's visible to the user (which is especially true with scrolling).

So the line you've linked to doesn't actually stop LCP candidates from being reported, it just tell this library that it's safe to report the last-reported candidates as "final" given that user interaction has occurred.

**Comment by neenhouse** [comment]
Alright, that makes sense, thanks @philipwalton !
