### ISSUE TITLE
Combined snippet for GA + GA4

### ISSUE THREAD

**Issue by siakaramalegos** [GoogleChrome/web-vitals#168]
Hi there, thanks for this handy script. I'm currently collecting on both legacy Google Analytics and GA4. I'm already sending this data to both, but using the GA snippet. I want to try building out the BigQuery/Data Studio dashboard from your I/O video. But, I'm not sure if I can since the snippets are slightly different. I'm guessing it's fine to have the extra properties, but the `value` one is different for CLS - would it be ok to send the integer version of CLS (so the legacy/top example below)?

```javascript
        gtag('event', name, {
          event_category: 'Web Vitals',
          // The `id` value will be unique to the current page load. When sending
          // multiple values from the same page (e.g. for CLS), Google Analytics can
          // compute a total by grouping on this ID (note: requires `eventLabel` to
          // be a dimension in your report).
          event_label: id,
          // Google Analytics metrics must be integers, so the value is rounded.
          // For CLS the value is first multiplied by 1000 for greater precision
          // (note: increase the multiplier for greater precision if needed).
          value: Math.round(name === 'CLS' ? delta * 1000 : delta),
          // Use a non-interaction event to avoid affecting bounce rate.
          non_interaction: true,

          // GA 4
          value: delta, // Use `delta` so the value can be summed.
          // Custom params:
          metric_id: id, // Needed to aggregate events.
          metric_value: value, // Optional.
          metric_delta: delta, // Optional.

          // OPTIONAL: any additional params or debug info here.
          // See: https://web.dev/debug-web-vitals-in-the-field/
          // metric_rating: 'good' | 'ni' | 'poor',
          // debug_info: '...',
          // ...
        });
```

**Comment by philipwalton** [comment]
I'm doing something very similar to what you want to do (sending data to both GA3 and GA4) in the [Web Vitals Report](https://web-vitals-report.web.app/) site, so perhaps you could take a look at [the code I'm using there](https://github.com/GoogleChromeLabs/web-vitals-report/blob/380f197d79634fba1985f61744483c83280bde4d/src/js/analytics.js#L139-L150) and adapt it for your needs?

**Comment by siakaramalegos** [comment]
That works! Thanks so much. It's actually the same thing I started testing yesterday. It's nice to see this full example with debug info too.
