### ISSUE TITLE
Considering not penalize pages with loading modal above?

### ISSUE THREAD

**Issue by qianshancun** [GoogleChrome/web-vitals#170]
Sometimes I HAVE to rearrange the DOM nodes a few seconds later after the user's input.

For instance, using [HTML2Canvas](https://github.com/niklasvh/html2canvas/releases) to create a local screenshot but with some updates to the DOM nodes (before taking the screenshot), while the updates are affected by some network response after the user's click action.

Here are the steps:

1. A user clicks the `submit` button.
2. A request is sent to remote, containing some information about the user.
3. The server calculates some results and tells the client to resize some `div#result`'s height from `200px` to `500px` - _Please note that the client doesn't know whether it's 500 or 600 or 700 before having the response_.
4. The client renders the `div#result` with HTML2Canvas.

During the process, it would bring a huge CLS because the time difference between user inputs at No.1 and server result No.3 might be very long (much longer than `500ms`). And it's very unfriendly to ask the user to do some action again after No.3

So what I am doing is to put a loading modal on the screen:

![image](https://user-images.githubusercontent.com/85496448/126737583-564a10ca-92bd-4b88-be32-71b3f46eda35.png)

However, this doesn't change the CLS penalization.

Is there any way the CLS detection could pardon this situation?

**Comment by philipwalton** [comment]
Thanks for the question, @qianshancun; however, this is probably not the best forum to discuss it since these issues are specific to the web-vitals JavaScript library.

Can you email your question to web-vitals-feedback@googlegroups.com?
