### ISSUE TITLE
performance.getEntriesByName is not a function. (In 'performance.getEntriesByName("first-contentful-paint")', 'performance.getEntriesByName' is undefined

### ISSUE THREAD

**Issue by huanghairong2312** [GoogleChrome/web-vitals#174]
performance.getEntriesByName is not a function. (In 'performance.getEntriesByName("first-contentful-paint")', 'performance.getEntriesByName' is undefined  .

in webvitals/getFCP.js
device: Iphone 
webvitals version：1.1.2

**Comment by philipwalton** [comment]
This is a duplicate of https://github.com/GoogleChrome/web-vitals/issues/172. In short, upgrading to version 2.0.1 of greater should fix the issue.
