### ISSUE TITLE
Will IE, Firefox and safari support LCP in the future?

### ISSUE THREAD

**Issue by zengzuo613** [GoogleChrome/web-vitals#175]

**Comment by qiuyaofan** [comment]
I also have this need, can you support it？

**Comment by philipwalton** [comment]
LCP is not a metric that can be easily polyfilled, so it is not something this library will support unless those browsers implement the native API.

If you would like to see support in those browsers, I'd recommend reaching out to them or filing bugs on their issue trackers expression your support for this feature.
