### ISSUE TITLE
Single page App and web-vital metrics 

### ISSUE THREAD

**Issue by rahul-raut** [GoogleChrome/web-vitals#176]
Hi Team,
I am working on angular single page app where when I hit search it shows results on the /results page without actually redirecting. All the routes are internally managed by angular. Is there any way to capture those metrics using web-vitals metrics?
On the home page I get the metrics but after that unless and until I reload the  page I didn't able to capture the metrics. 
Any help appreciated!

Thanks,
Rahul

**Comment by philipwalton** [comment]
See the discussion here: https://github.com/GoogleChrome/web-vitals/issues/119
