### ISSUE TITLE
Should headless chrome bot traffic report metrics?

### ISSUE THREAD

**Issue by SvenPetroll** [GoogleChrome/web-vitals#182]
Hi,

we're using this library to collect web vital metrics in our application. As an e-commerce business we see a lot of bot traffic crawling our pages and we noticed that they're reporting web-vitals (even LCP) to our analytics backend. This causes a lot of wrong data, especially during the night where bot traffic is on the same level as normal customer traffic.

We can see that those spikes disappear after blocking specific bots. But since we don't particularly care about bots and blocking bots is a never ending game of cat and mouse, this isn't a solution and for all we know, Google might not filter this data either and we would need to find a solution that improves the metrics even for headless chrome bots.. 

Do you have any advice how to handle this issue?

**Comment by philipwalton** [comment]
My suggestion would be to remove the bot data if you can reliably identify it. The point of RUM is to better understand the experience of real users, and bots/headless/webdriver/etc are not real users.

> ...and for all we know, Google might not filter this data either...

I can't comment too much on what Google does to fight spam/bots, can I can point you to CrUX documentation that explains where the data comes from: https://developers.google.com/web/tools/chrome-user-experience-report#metrics

Specifically this section:

> The Chrome User Experience Report is powered by real user measurement of key user experience metrics across the public web, aggregated from users who have **opted-in to syncing their browsing history**, have **not set up a Sync passphrase**, and have **usage statistic reporting enabled**...

I hope that is helpful!
