### ISSUE TITLE
v1.1.2 or later can crash apps on Opera Mini extreme data saving mode

### ISSUE THREAD

**Issue by jroebu14** [GoogleChrome/web-vitals#185]
Hi,

We first reported a problem with v1.1.2 here https://github.com/GoogleChrome/web-vitals/issues/159 which we submitted a fix for.

However when we upgraded to v2.0.1, which contains the fix, we discovered the crash still happened on Opera Mini.

To mitigate this we resorted to [wrapping the performance metrics collection functions in a try/catch and logged out the error](https://github.com/bbc/psammead/pull/4573/files). This is the error we see - `Undefined variable: performance`.

It seems the Performance API is not supported at all in Opera Mini extreme data saving mode - https://caniuse.com/?search=performance

We get a moderate amount of traffic on this browser so it would be great if we could help expand support to this browser again. If supporting this browser is too tricky then consumers should be aware that they may have to handle errors coming from this package if they need to serve an audience that use Opera Mini.

Happy to help with this issue.

Thanks!

**Comment by philipwalton** [comment]
Hmmm, I'm happy to add reasonable checks to avoid errors, but I can't actually reproduce this myself.

I've downloaded Opera Mini and turned on extreme data saver mode and I still see the global `performance` object. (Testing on `OPR/60.0.2254.59405`).

Do you know what version of Opera Mini you're seeing the error in?

**Comment by jroebu14** [comment]
Brilliant! Thanks for this!
