### ISSUE TITLE
Samsung internet 15.0 support

### ISSUE THREAD

**Issue by rubenlangius** [GoogleChrome/web-vitals#191]
Hi, 

I've implemented the web-vitals package in a project with a large user base so lots of different users and browsers and I've noticed that there seems to be a lack of support for the Samsung internet 15.0 browser. 

Since integration I've logged 3k users that use this version of the samsung internet browser and that trigger the following error: 
`Type Error: u is not a function` in this snippet of my vendor bundle.
```
{snip} pture:!0})})),c(d,!0),f((function(r){o=l("LCP"),n=p(e,o,t),u((function(){u((function(){o.value=performance.now()-r.timeStamp,P[o.id]=!0,n(!0 {snip}
```
Which seems to be related to this code: 
```
requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          metric.value = performance.now() - event.timeStamp;
          reportedMetricIDs[metric.id] = true;
          report(true);
        });
      });
```
in `web-vitals/src/getLCP.ts`

The documentation states that there is full support for chromium browsers which is the case for samsung internet afaik. And [this issue](https://github.com/GoogleChrome/web-vitals/issues/37) also mentions that it is considered not necessary to detect browser type to toggle the tracking on or off. 

Therefore I decided to reach out, to find out if this is a known issue and to see if we can possibly fix this.

**Comment by philipwalton** [comment]
What version of the library are you using?

The minified source code you've pasted above seems to have minified `requestAnimationFrame()` to `u()`, which I don't see being the case in any of the published module versions I'm looking at.

Is it possible your build process has minified this code incorrectly?

**Comment by rubenlangius** [comment]
thanks for the quick reply. 

I'm using version 2.1.2, I agree that `requestAnimationFrame()` is minified to `u()`. We are not doing any special things in our build process. We basically store all node modules in 1 vendor bundle and that gets obviously minified and gzipped. 

I would assume that if our minification is the problem that all other browsers would have similar issues, and this is not the case. Everything is running smooth except for Samsung Internet version 15.0.

**Comment by philipwalton** [comment]
Can you point me to a live example of this?

**Comment by rubenlangius** [comment]
Sure: https://www.belsimpel.nl/telefoon

**Comment by rubenlangius** [comment]
Thanks very much, I will look into this!
