### ISSUE TITLE
Cumulative Layout Shift (CLS) problem again

### ISSUE THREAD

**Issue by mdromed** [GoogleChrome/web-vitals#198]
I don't know why but console is shown this (see pic) How is it possible that console is marking all that entire block as CLS contribution? It should be shown as unique small parts

That is the url to try:
https: //www . b e b e m o v i l . com/inglesina-quid-2-silla-de-paseo-id575  (without spaces)
Image link: https://i.stack.imgur.com/she3k.png

and...

this also happens... there are no cls changes, however CLS value is so bad... I don't understand it (it is with this url https: //www.b e b e m o v i l.com/inglesina-aptica-quattro-carrito-bebe-trio-3-piezas-id567 )
Image link: https://i.stack.imgur.com/B0txx.png

Please i need help @philipwalton , @rviscomi 
Thanks so much in advance

**Comment by Tiggerito** [comment]
A test using the Chrome Performance report indicates there are a bunch of shifts within that element. I suspect CSS and font loading and causing multiple small shifts, all adding up to a CLS.

I moved all your CSS resources to the head section so that they become a high priority. And I preloaded a font:

<link rel="preload" as="font" href="https://fonts.gstatic.com/s/montserrat/v15/JTURjIg1_i6t8kCHKm45_cJD3gnD_g.woff2" type="font/woff2" crossorigin>

No more layout shifts.

**Comment by mdromed** [comment]
> A test using the Chrome Performance report indicates there are a bunch of shifts within that element. I suspect CSS and font loading and causing multiple small shifts, all adding up to a CLS.
> 
> I moved all your CSS resources to the head section so that they become a high priority. And I preloaded a font:
> 
> No more layout shifts.

Great answer dear @Tiggerito
I will try it asap and will tell u about it.
How can a font to be preloaded?
Should i  preload icon font too?

**Comment by Tiggerito** [comment]
The editor removed my example of the preload tag.

`<link rel="preload" as="font" href="https://fonts.gstatic.com/s/montserrat/v15/JTURjIg1_i6t8kCHKm45_cJD3gnD_g.woff2" type="font/woff2" crossorigin>`

One issue with this is that the font URL may change in the future, making the preload a waste of time. Or the fonts used change. Some host the font locally to take control.

**Comment by mdromed** [comment]
> A test using the Chrome Performance report indicates there are a bunch of shifts within that element. I suspect CSS and font loading and causing multiple small shifts, all adding up to a CLS.
> 
> I moved all your CSS resources to the head section so that they become a high priority. And I preloaded a font:
> 
> No more layout shifts.

GREAT MY FRIEND.
IT HAS WORKED.
CLS is now in green range.

Thank you very much @Tiggerito
