### ISSUE TITLE
Getting error in repo

### ISSUE THREAD

**Issue by FahimFBA** [GoogleChrome/web-vitals#202]
Whenever I am trying to star the repo, I am getting the following.
![image](https://user-images.githubusercontent.com/64195132/154449781-9be90ab2-d7af-4aae-bb81-50c6a82cab2f.png)

Also, I am getting this as well.

![image](https://user-images.githubusercontent.com/64195132/154449861-6ccd6658-23b5-4f0b-b45a-18005e5bb0cd.png)

I am not sure if others are also facing the exact issue or not.

**Comment by philipwalton** [comment]
I'm not 100% sure, but if I had to guess I'd say the problem is you're using some sort of content blocker extension that's blocking all network requests for resources with the string `"web-vitals"` in the name.

**Comment by FahimFBA** [comment]
I have tried using other browsers, after removing all of the extensions and clearing the cache. None of the methods are working.

**Comment by FahimFBA** [comment]
Thanks a lot. After removing ad-blockers, all of them are working correctly.
