### ISSUE TITLE
Performance statistics in Hybrid development Webview are not supported

### ISSUE THREAD

**Issue by haohongyang1** [GoogleChrome/web-vitals#204]
Self-testing found poor mobile compatibility for the PerformanceObserver, with 80 per cent of models failing to get performance data
![screenshot-20220221-182953](https://user-images.githubusercontent.com/41784724/154937451-e54312f5-5a41-4f68-b21c-a4780914b94b.png)
![screenshot-20220221-182856](https://user-images.githubusercontent.com/41784724/154937472-ec45c6e3-e9ca-411f-aa5f-b288d27b1b62.png)

**Comment by philipwalton** [comment]
This package is not expected to work on iPhone X, see the [browser support](https://github.com/GoogleChrome/web-vitals#browser-support) section of the README for more details.

Regarding these warnings, can you clarify what code you're running that's triggering them?

**Comment by haohongyang1** [comment]
The warning information comes from the test of Performanceobserver API in different mobile phone models.
Does the web-vitals library support H5 performance statistics in hybrid development?

**Comment by philipwalton** [comment]
> The warning information comes from the test of Performanceobserver API in different mobile phone models.

So, to be clear, you're not seeing those warning while running the code in the library, you're just seeing those warnings when trying to use the `PerformanceObserver` API, correct?

**Comment by haohongyang1** [comment]
Yes

**Comment by haohongyang1** [comment]
I'm trying to find out why web-vitals can't get the performance data of hybrid applications, so I'm testing PerformanceObserver.

**Comment by haohongyang1** [comment]
> > The warning information comes from the test of Performanceobserver API in different mobile phone models.
> 
> So, to be clear, you're not seeing those warning while running the code in the library, you're just seeing those warnings when trying to use the `PerformanceObserver` API, correct?



> I'm trying to find out why web-vitals can't get the performance data of hybrid applications, so I'm testing PerformanceObserver.

**Comment by haohongyang1** [comment]
> > The warning information comes from the test of Performanceobserver API in different mobile phone models.
> 
> So, to be clear, you're not seeing those warning while running the code in the library, you're just seeing those warnings when trying to use the `PerformanceObserver` API, correct?

I would like to ask whether there is any plan to be compatible with Hybrid App. I have an alternative to PerformanceObserver, which can be used to replace it. Do you need me to provide a solution.

**Comment by tunetheweb** [comment]
There are no plans to allow this library to work without Performance Observers as browsers without Performance Observer support will not support the majority of the metrics this library provides with potentially only TTFB able to be supported.
