### ISSUE TITLE
Request for support: responsiveness metric

### ISSUE THREAD

**Issue by borisschapira** [GoogleChrome/web-vitals#208]
A note to remember that if the test is conclusive, it could be relevant to add to this library the support of the [responsivement metric](https://web.dev/responsiveness/).

**Comment by jpvincent** [comment]
Current demo implementation, as revised by @anniesullie & @paulirish will catch the value for Interaction / group of events : https://gist.github.com/anniesullie/16814ef9e888fec45e0946da303f55ac

The code to compute the correct value with the "high quantile approximation, option 2" ([source](https://web.dev/responsiveness/#aggregation-strategies-options)) has yet to be written, though.

**Comment by philipwalton** [comment]
Thanks for the reminder. Support for the new responsiveness metric is definitely planned. I'll update this issue once it's been added.
