### ISSUE TITLE
Size of library in README.md

### ISSUE THREAD

**Issue by alcazes** [GoogleChrome/web-vitals#211]
In the READEME.md it is mentioned:

> The web-vitals library is a tiny (~1K),

When I checked on https://unpkg.com/browse/web-vitals@2.1.4/dist/ the library is actually 4.36 kB, could this be updated please ?

**Comment by jridgewell** [comment]
That's considering the file size without compression. With compression, it's ~1.5kb:

```bash
$ curl -s https://unpkg.com/web-vitals@2.1.4/dist/web-vitals.js | gzip -9 -c | wc -c
    1713
$ curl -s https://unpkg.com/web-vitals@2.1.4/dist/web-vitals.js | brotli --best | wc -c
    1524
```

**Comment by tunetheweb** [comment]
Since clarified and now reads:
> The web-vitals library is a tiny (~1.5K, brotli'd)
