### ISSUE TITLE
INP values incorrect when split over blur/focus

### ISSUE THREAD

**Issue by nornagon** [GoogleChrome/web-vitals#229]
It is possible to cause `onINP` to produce an arbitrarily high INP value by the following:

1. Mouse down on any element
2. Switch away from the tab
3. Wait an arbitrary amount of time
4. Switch back to the tab

`onINP` will then report a value for INP that includes the amount of time spent in (3), i.e. if you switched away from the tab for 5 minutes, you'll get an INP of 5 minutes.

This seems like a measurement error to me; it's certainly not very useful to include it! Perhaps this could be accounted for in this library?

**Comment by philipwalton** [comment]
Thanks for the report. I *think* this is the same issue outlined in this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1312568

If so, then once this bug is fixed the problem won't exist in the library.

**Comment by nornagon** [comment]
Ah, yes, that looks related. Hopefully that gets some attention soon! It's fairly unclear how to get useful data out of this at scale in the face of that issue 😅

**Comment by tunetheweb** [comment]
The [associated Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1312568) was fixed in Chrome so closing this under the assumption it's now no longer an issue. Feel free to reopen if that's not the case.
