### ISSUE TITLE
INP value not collected when source code is minified

### ISSUE THREAD

**Issue by golden8520** [GoogleChrome/web-vitals#230]
Hello,

I am using "3.0.0-beta.2" of WV to collect the INP value. On my development environment everything looks ok i have a value of INP.
But when i pushed the project on production environment, i am not seeing a value of INP, while i debug the ReportCallback inside onINP was not called.
Next, i found how to reproduce the issue on the dev environment, by activating the terser on the rollup.config to minify my files.

Any idea how to resolve this please ?

**Comment by philipwalton** [comment]
I suspect this is more of an issue with your setup than an issue with this library, but it's hard to say based on just the information you've given.

The `web-vitals` JS library is minified using terser, and I used it on several projects that are also minified using terser, so I know that terser itself is not the problem.

I suspect the way you're importing the library is causing terser to believe that you're never running the code, and so it's removing it—but without more information I can't say for sure.

**Comment by golden8520** [comment]
Thank you for your answer, but i forgot to mention that i am already using other metrics like CLS, FCP, FID, LCP... and i have no problem with them when the project is deployed to production.
I have just added this new metric to my class of Metric collector, and while i tested it without terser on dev environment it works very well.
Considering the minified code on prod environment, i verified the source code and i didn't find that terser is removing it, as you can see on my screenshot.
![image](https://user-images.githubusercontent.com/77736783/169979394-58cde088-9720-454e-b879-3c5e6515388a.png)

**Comment by philipwalton** [comment]
Do you have this code published anywhere where I could take a look?

Also, is it possible that the reason you're not getting reports is, in production, your interactions are all very fast because the code is fully optimized?

**Comment by golden8520** [comment]
This is the part of code that we use to collect the INP value, in the same class and we the same method we collect the other metrics.

`    this.collectors = new Set();
    this.collectors.add(() =>
      onINP(
        ({ value }) => {
          this.inpCollected = new NullableNumber(value);
          log(`[MetricCollector] INP collected with result: ${value}`);
        },
        { ...reportOptions, durationThreshold: 16 }
      )
    );`

And here, i will share with you two screenshots to show you that our metrics values collected are equals to WV extension.
![wv payload](https://user-images.githubusercontent.com/77736783/170215735-5925a7c4-54a7-4f19-b4fd-3c051d57e343.png)
![wv ext](https://user-images.githubusercontent.com/77736783/170215765-e83bc885-d660-4e8d-88c8-ee1c22c5b393.PNG)

**Comment by golden8520** [comment]
I fixed the issue by adding ```javascript
 "interactionId",
            "interactionCount",
            "durationThreshold",
``` to my terser reservered array.
What do you think ?

**Comment by jschulte** [comment]
For what it's worth, I use this to minify my JS files that use this library and have no issues:

```npx terser index.js --compress --mangle --output index.min.js
