### ISSUE TITLE
LCP reporting depends on how early getFCP was called

### ISSUE THREAD

**Issue by dmitriyshashkin** [GoogleChrome/web-vitals#236]
If getLCP is called after the user input has happened the callback function is not exucuted until the next user input. If user leaves the page without any additional input I suppose the tracking doesn't occur at all. If the cwv tracking code is loaded as an asynchronous external js, whether the tracking occurs is dependent on whether the getLCP is called before the last user input or after.

Test page to reproduce that. Each second a new getLCP call happens. If you click on the red square the previous getLCP calls yeild callbacks and corresponding messages are displayed. Yet all the getLCP calls that happen after the click won't yield callbacks until the next click happens.

https://jsfiddle.net/rbe9fhyo/

**Comment by philipwalton** [comment]
> If getLCP is called after the user input has happened the callback function is not exucuted until the next user input.

Yes, this is expected. Waiting to report LCP until user input has no effect on what the LCP value is, it just dictates how soon it can be reported.

> If user leaves the page without any additional input I suppose the tracking doesn't occur at all.

LCP is always reported either at user input or when the page is backgrounded or unloaded, so it doesn't matter if the user never interacts with the page after `getLCP()` is called. It also doesn't matter when `getLCP()` is called, the same LCP value will always be reported for that page.

> If the cwv tracking code is loaded as an asynchronous external js, whether the tracking occurs is dependent on whether the getLCP is called before the last user input or after.

Again, it doesn't matter when the library is loaded or when `getLCP()` is called, the same LCP value will always be reported for the current page.

> Test page to reproduce that.

This test page confirms what I said above. And as you can see, if you switch tabs or navigate away from the page, all of the LCP callbacks that haven't yet fired, will fire. And the exact same LCP value is logged in each case.
