### ISSUE TITLE
Usage on Angular routed applications?

### ISSUE THREAD

**Issue by guilhermevrs** [GoogleChrome/web-vitals#24]
Hello,
First of all, great work!

I am wondering: Is it possible to use this tool on Angular routed applications?

I can definitely see the usage on the very first page of my application, since it's like any other web application. My question is more related to subsequent pages in my application flow. 

Can this be able to understand that there is a route change and, therefore, restart the metric?
I haven't checked the code, but if there is nothing browser API related, but couldn't the application itself tells the tool that there is a route change? In case, of course, you can't directly detect it.

Cheers!

**Comment by philipwalton** [comment]
> I am wondering: Is it possible to use this tool on Angular routed applications?

It is not. These metrics (and their underlying web APIs) currently all apply to the page load—which means even if you used them after an SPA soft navigation, they would still report values for the initial page load.

Work is currently being done to create metrics that measure SPA navigations, but that work is still in the beginning stages.

**Comment by simeyla** [comment]
Well surely that's what's most important? The initial page load. 
At least as far as analytics that affect Lighthouse and Google page-speed metrics.
Where should this be put in an Angular application?
