### ISSUE TITLE
Is TTFB being properly calculated?

### ISSUE THREAD

**Issue by carlesnunez** [GoogleChrome/web-vitals#25]
Hello I'm probably wrong but according to [this article](https://developers.google.com/web/fundamentals/performance/navigation-and-resource-timing) from web dev TTFB can be calculated doing the next:

```javascript
// Time to First Byte (TTFB)
var pageNav = performance.getEntriesByType("navigation")[0];
var ttfb = pageNav.responseStart - pageNav.requestStart;
```

But on the web-vitals implementation of TTFB we are doing the next:

```javascript
      const navigationEntry = performance.getEntriesByType('navigation')[0] ||
          getNavigationEntryFromPerformanceTiming();

      metric.value = metric.delta =
          (navigationEntry as PerformanceNavigationTiming).responseStart;
```

I'm a bit confused of which should be the metric calculated.

Link to the file:
https://github.com/GoogleChrome/web-vitals/blob/949744395cd281483bdfa9f3a663138fb55d4a5e/src/getTTFB.ts#L106

Thank you in advance

**Comment by Zizzamia** [comment]
Thank you @carlesnunez to pointing this out! I had a similar question and @philipwalton explained the decision behind this in this comment https://github.com/GoogleChrome/web-vitals/pull/9#issuecomment-623007716

**Comment by philipwalton** [comment]
Sorry for the confusion. TTFB is the delta between `startTime` and `responseStart`. I've updated that page to remove the misleading information: https://github.com/google/WebFundamentals/pull/8690

**Comment by carlesnunez** [comment]
Hey @philipwalton thank you for the response! :)
