### ISSUE TITLE
When will v3 be stable?

### ISSUE THREAD

**Issue by AbhiPrasad** [GoogleChrome/web-vitals#250]
Hey!

I help maintain the [Sentry browser performance monitoring SDK](https://github.com/getsentry/sentry-javascript/tree/master/packages/tracing), which wraps the `web-vitals` library. Would love to start testing web-vitals v3 - is there a timeline around when the API will become stable (either a release candidate or full release)?

We'd be happy to help test things for you folks, just let us know!

**Comment by philipwalton** [comment]
I just published the first v3 release candidate:
https://github.com/GoogleChrome/web-vitals/blob/v3.0.0-rc.0/CHANGELOG.md#v300-rc0-2022-07-26

If there are no major issues, I'd like to release v3 in the next week or so.

**Comment by philipwalton** [comment]
It look a bit longer than I thought, but v3 has now been released: https://github.com/GoogleChrome/web-vitals/blob/main/CHANGELOG.md
