### ISSUE TITLE
[Question] Doc on expanding browser support beyond Chromium

### ISSUE THREAD

**Issue by cwli24** [GoogleChrome/web-vitals#255]
Hi, I'm interested in using `onINP`, but the browser support section notes that only Chromium-based supports it at this time and not Safari or Firefox, presumably due to usage of web API not avail in those browsers.

If we want to manually implement support for them, what's the outline on which method(s) are problematic in this regard? (Could include the other metrics in this inquiry too.) Separately, are there plans to support those browsers?

Edit: I just noticed that INP's web.dev page warns:
> Gathering INP metrics in the field will only work on browsers that [fully support the Event Timing API](https://caniuse.com/mdn-api_performanceeventtiming), including its interactionId property.

Safari doesn't currently support Event Timing at all, so that makes sense. However, Firefox shows full support since v89. Is the README not updated, or does [onINP really not support Firefox](https://github.com/GoogleChrome/web-vitals/blob/4ca38ae64b8d1e899028c692f94d4c56acfc996c/src/onINP.ts#L161) atm?

**Comment by philipwalton** [comment]
> However, Firefox shows full support since v89. Is the README not updated, or does [onINP really not support Firefox](https://github.com/GoogleChrome/web-vitals/blob/4ca38ae64b8d1e899028c692f94d4c56acfc996c/src/onINP.ts#L161) atm?

Firefox does not support the `interactionId` property, which was recently added to the API and is required to calculate the INP metric.

**Comment by fateme3** [comment]
I have the same question, I need to know CLS and LCP when user is using firefox or edge browser , but they don't support the library...does anybody have any solution?

**Comment by tunetheweb** [comment]
Edge is Chromium-based so has full support of all the metrics. Firefox does not currently support LCP nor CLS.

**Comment by fateme3** [comment]
@tunetheweb do you have any suggestions to measure LCP and CLS of a js based web application in firefox ?

**Comment by tunetheweb** [comment]
This is not possible until Firefox implements the underlying APIs necessary. Best you can do for now is measure in Chromium-based browsers and hope it’s somewhat representative for Firefox users.
