### ISSUE TITLE
Any Analysis Service?(like sentry)

### ISSUE THREAD

**Issue by chesscai** [GoogleChrome/web-vitals#26]

**Comment by philipwalton** [comment]
Any analytics service that tracks metrics. It looks like Sentry is an error tracking service, so probably not.

**Comment by thearegee** [comment]
@philipwalton Sentry recently added in support for performance and it looks like web vitals is making its way in too
https://github.com/getsentry/sentry-javascript/pull/2909
https://github.com/getsentry/sentry-javascript/pull/2624
