### ISSUE TITLE
attribution property can be undefined

### ISSUE THREAD

**Issue by ArgonAlex** [GoogleChrome/web-vitals#264]
Using the attribution build, I was seeing `Uncaught TypeError: Cannot read property 'largestShiftTarget' of undefined` errors in our client logs. Unfortunately this means we missed tracking some CLS events until we could deploy a fix with a truthy check for `attribution`.

Our usage is very similar to the [documentation](https://github.com/GoogleChrome/web-vitals#send-attribution-data), which will also run into this error because there is no truthy check for `attribution`.

It seems that either:
a) The TS typings and documentation should be updated to take into account `attribution` possibly being undefined
or
b) The code should be updated so attribution is always at least an empty object

**Comment by philipwalton** [comment]
The intention is that the `attribution` property is always present when using the attribution build, so the documentation is correct and if you're finding cases where that's not happening then it may be a bug.

Looking at the code for `onCLS()` now, it does seem like it could be possible if the user were on a browser that supports CLS but doesn't support the `LayoutShiftAttribution` interface, which looks like was true for Chrome version 77-83.

I will update the code to ensure there's always an attribution property, but to make sure nothing else is going on, are you able to see what browser and version the users reporting this error had?

**Comment by ArgonAlex** [comment]
Thanks for looking into this!

Our logs are from Sept 15 (when we started using the attribution build) to Sept 28 (when our fix was deployed). From those logs I'm seeing almost every Chrome version >= 62 across all of the major platforms, Android Chrome 105 being the most common (which makes sense since it was the generally the most common Chrome version for our users as of these log dates). So it seems to be more than just Chrome 77-83.

**Comment by philipwalton** [comment]
This should be fixed in version [`3.0.3`](https://github.com/GoogleChrome/web-vitals/blob/main/CHANGELOG.md#v303-2022-10-04).
