### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startTime')

### ISSUE THREAD

**Issue by xepozz** [GoogleChrome/web-vitals#274]
I faced with the error when I deployed my project to production. But I thought that it is relevant to my project.
As we can see, the error happens from time to time. 
But I have an interesting thing. I've disabled `web-vitals` for the production environment. 
`index.ts`:
```js
// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
if (process.env.NODE_ENV === 'development') {
  const {reportWebVitals} = require('./reportWebVitals');
  reportWebVitals();
}
```
And here is `reportWebVitals.ts`:
```ts
let reportWebVitals = () => null;
// TODO: setup Google Analytics for web-vitals
// @link https://github.com/GoogleChrome/web-vitals
if (process.env.NODE_ENV === 'development') {
  const WV = require('web-vitals');

  reportWebVitals = (onPerfEntry?: typeof WV.ReportHandler) => {
    if (onPerfEntry && onPerfEntry instanceof Function) {
      WV.getCLS(onPerfEntry);
      WV.getFID(onPerfEntry);
      WV.getFCP(onPerfEntry);
      WV.getLCP(onPerfEntry);
      WV.getTTFB(onPerfEntry);
    }
  };
}

export {reportWebVitals};
```

As we can see here is at least 2 different check. The first is `env !== dev` and the second is "callback is not undefined"
I use CRA scripts and I know that the node_env is `production`.
<img width="293" alt="image" src="https://user-images.githubusercontent.com/6815714/200307762-db408489-6276-4a57-841b-3203fbe34809.png">

Anyway, I install my deps without `devDependencies` where `web-vitals` is placed.
`RUN npm ci --no-audit --progress=false --prefer-offline --omit=dev`
Here is my lock file:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/6815714/200308090-ca080334-b18e-422f-b767-9fe6b06f80fb.png">
```json
"web-vitals": {
  "version": "3.0.4",
  "resolved": "https://registry.npmjs.org/web-vitals/-/web-vitals-3.0.4.tgz",
  "integrity": "sha512-Yau8qf1AJ/dm6MY180Bi0qpCIuWmAfKAnOqmxLecGfIHn0+ND3H4JOhXeY73Pyi9zjSF5J4SNUewHLNUzU7mmA==",
  "dev": true
}
```

BUT
I see the error on the production. How can it be possible? Is there any methods to debug that case?

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/6815714/200305978-a47cfde8-b16d-4bc4-851a-d0bdb7824ff6.png">

**Comment by tunetheweb** [comment]
This library has changed quite a but since this issue was reported and typescript report has been considerably improved. Please check the latest version and let us know if this is still and issue by raising a new issue with the details.

**Comment by szc807414589** [comment]
@tunetheweb  This problem still seems to exist, the version I use is 4.2.1
