### ISSUE TITLE
Is CLS actually DCLS?

### ISSUE THREAD

**Issue by wildlyinaccurate** [GoogleChrome/web-vitals#29]
Judging by the implementation, it looks like the "CLS" that web-vitals reports is actually [DCLS](https://github.com/WICG/layout-instability#cumulative-scores). Is that right?

**Comment by philipwalton** [comment]
Yes, we often use these terms interchangeably, but it's probably worth clarifying in the README that this library does not track layout shifts in iframes.

**Comment by wildlyinaccurate** [comment]
Thanks for clarifying @philipwalton!

**Comment by philipwalton** [comment]
I'm going to re-open this as a reminder to update the documentation with clarification as well.
