### ISSUE TITLE
Potential memory leak with INP interactions?

### ISSUE THREAD

**Issue by jasonwilliams** [GoogleChrome/web-vitals#292]
I noticed `onINP` only stores the 10 worst interactions and throws away the rest to avoid [unnecessary memory usage](https://github.com/GoogleChrome/web-vitals/blob/main/src/onINP.ts#L44-L46). But it seems most entry's have the same interactionId of [0](https://w3c.github.io/event-timing/#dom-performanceeventtiming-interactionid). (click, pointer, mousedown events etc)

This means most of them end up falling into the same interaction object which does still fill up it's entries property https://github.com/GoogleChrome/web-vitals/blob/main/src/onINP.ts#L76

Just wondering if I'm missing something here or should this property also be checked for only 10 entries.

**Comment by tunetheweb** [comment]
Isn't this handled by this code?

https://github.com/GoogleChrome/web-vitals/blob/39f178242afbb96dca3d48b216d60e7cd4cfa633/src/onINP.ts#L150-L153

Now we also do consider the [FID entry](https://github.com/GoogleChrome/web-vitals/blob/39f178242afbb96dca3d48b216d60e7cd4cfa633/src/onINP.ts#L163-L174) but there should only be one of them.

**Comment by jasonwilliams** [comment]
Ah I see so this is filtering out some entries we don't care about, usually ones that aren't a user interaction? 
I noticed that  `pointerout`, `pointerleave`, `pointerover`, `pointerenter`, `mouseout`, `mouseenter` all have 0, is this because they're "continuous events" and not "interaction events"?

**Comment by tunetheweb** [comment]
Correct, for INP [only the following interactions are counted](https://web.dev/inp/#whats-in-an-interaction):

> As far as INP goes, **only the following interaction types are observed**:
>
> - Clicking with a mouse.
> - Tapping on a device with a touchscreen.
> - Pressing a key on either a physical or onscreen keyboard.

**Comment by jasonwilliams** [comment]
Thanks for clarifying @tunetheweb
