### ISSUE TITLE
Allow installation as simple <script> tag

### ISSUE THREAD

**Issue by mpchadwick** [GoogleChrome/web-vitals#30]
I want to install this by just doing something like `<script src="web-vitals.js"></script>` and then call the functions from the documentation to track the metrics, but it seems that's not a supported way of using this? I'm not really that familiar with JavaScript modules. It would be nice if there was a simple, "old school" way to install this.

**Comment by philipwalton** [comment]
You can do this using a service like unpkg.com, I've added an example to the README showing how.
