### ISSUE TITLE
Support for `Server-Timing`

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/web-vitals#302]
If a document includes `Server-Timing` headers, it could be useful to report that as TTFB diagnostic data in the RUM beacon. Is there anything this library can do to better support this kind of data?

This is a follow up to https://github.com/GoogleChrome/web-vitals/issues/203 by @malchata which originally proposed tracking `Server-Timing`, but AFAICT it wasn't ultimately added to the attribution build. Is there any additional context behind that decision, or worth reevaluating?

**Comment by philipwalton** [comment]
Did you have a specific API design idea in mind? Right now it's pretty easy to get server timing data in either the standard or attribution build:

```js
onTTFB((metric) => {
  console.log(metric.entries[0]?.serverTiming);
});
```

Given that server timing info so site-specific, I'm not sure if we need more sugar on top of what we already have?

**Comment by malchata** [comment]
I think a bit of sugar could make this a bit more approachable, IMO:

```js
onTTFB((metric) => {
  console.log(metric.serverTiming);
});
```

**Comment by tunetheweb** [comment]
Adding the `serverTiming` value to the [TTFB attribution object](https://github.com/GoogleChrome/web-vitals#ttfb-attribution) could be one way to surface this more readily, rather than someone knowing how to grab this via `metric.entries[0]?.serverTiming`.

Seems inline with how the other metrics were handled for #203

**Comment by philipwalton** [comment]
If you're using the attribution build, you can get the server timing value like this:

```js
onTTFB((metric) => {
  console.log(metric.attribution.navigationEntry?.serverTiming);
});
```

Which isn't much different from @malchata's example:

```diff
+ console.log(metric.attribution.serverTiming);
- console.log(metric.attribution.navigationEntry?.serverTiming);
```

Every other property of each attribution object is a calculation of some sort, so it feels a bit arbitrary to add sugar for this one and not others. And if we add it for others then we're increasing code size quite a bit for values that most people aren't using.

**Comment by tunetheweb** [comment]
Think I'm with @philipwalton now. But let's document this as an example to make it more obvious how to access. Opened #324 for that.
