### ISSUE TITLE
[question] Regarding rating for a given session

### ISSUE THREAD

**Issue by gbrlmtrz** [GoogleChrome/web-vitals#303]
Hello! I was wondering what is the criteria to rate an user session as either ['good' | 'needs-improvement' | 'poor'](https://github.com/GoogleChrome/web-vitals#metric) when looking at all the metrics as a whole.

Two examples/questions:

We have a session with _good_ LCP and _good_ CLS but the FID event is never fired as the user never interacted with the page, could we rate this session as **good**?

Then, we have another session, this one with _good_ LCP, _good_ FID and _poor_ CLS, would this session be rated as **poor**?

**Comment by tunetheweb** [comment]
The three Core Web Vitals are rated independently.

PageSpeed Insights does give an overall rating if all three pass as a high level indicator, but we advise sites to look at all three web-vitals separately.

If you are asking about Search, I'd refer you to [their documentation on this](https://support.google.com/webmasters/thread/104436075/core-web-vitals-page-experience-faqs-updated-march-2021?hl=en#:~:text=Q%3A%20How%20does%20page%20experience%20ranking%20work%20with%20respect%20to%20the%20published%20guidance%20on%20what%20values%20for%20Core%20Web%20Vitals%20are%20considered%20in%20the%20%E2%80%9Cgood%E2%80%9D%20threshold%3F).

For sites with no interactions, this will still count as a "Good" FID.

**Comment by gbrlmtrz** [comment]
Hey @tunetheweb thank you very much! That answers my question perfectly!
