### ISSUE TITLE
Docs should mention "when to load"

### ISSUE THREAD

**Issue by kurtextrem** [GoogleChrome/web-vitals#304]
To some it might be obvious, but the readme does not mention when to load the library. It mentions install, it mentions how to use (the methods of the lib), integrations in other stuff, but not "when to load".

Only in this [Codelab](https://codelabs.developers.google.com/codelabs/web-vitals-google-analytics-bigquery#1) it is mentioned
> Copy this module script, and paste it **just before the closing `</body>` tag**.

Not everyone reads this Codelab, and I also don't think everyone using the `web-vitals` knows what to do best. 
Questions like:
- "Can/Should I lazy load the lib?" 
- "Do I need to load it as early as possible to not miss any values?" 
- "Do I register the callbacks on DOMContentLoaded/onLoad/using requestIdleCallback?" 

are open questions I can think of in the environment of performance, because there is no guideline.

**Comment by tunetheweb** [comment]
Have a look at the wording in #305 and let me know if that is clear enough.

**Comment by kurtextrem** [comment]
To me yes. Thank you!

**Comment by tunetheweb** [comment]
Closed with #305
