### ISSUE TITLE
getLargestLayoutShiftSource just gets the first one

### ISSUE THREAD

**Issue by Tiggerito** [GoogleChrome/web-vitals#309]
I noticed in my CLS source report that it seemed to be choosing the wrong element. So I looked at the code, and it looks like it picks the first and not the largest source for a specific layout shift. In my case, there were 5 sources for the largest shift, where the first one was the smallest. Hence the report was misleading.

[src/attribution/onCLS.ts](https://github.com/GoogleChrome/web-vitals/blob/main/src/attribution/onCLS.ts)
```
const getLargestLayoutShiftSource = (sources: LayoutShiftAttribution[]) => {
  return sources.find((s) => s.node && s.node.nodeType === 1) || sources[0];
};
```
Wouldn't it make sense to return the source that had the most effect on the largest shift?

**Comment by philipwalton** [comment]
The first source is typically closest in the DOM to the actual cause of the shift, and so by picking the first one (rather than the largest) I felt it would be easiest for people to debug.

For example, if an unsized image loads in on a page and then pushes all the subsequent content down, I think it's most helpful to report the element that moved that is closest to the image. If we report an element further down the page might be less clear—even if that is a larger element.

**Comment by Tiggerito** [comment]
To give an example from the case that got our attention.

The second CLS cluster is chosen, which had a score of 0.39, so quite bad.

The first element in the cluster, which is the one reported, is a small shift in the top-right navigation. In fact, the shift was a reduction in its width, so it did not affect anything. It went from 577x26 to 495x26. So nothing.

The second element was the main menu changing its height and margin. This caused all below it to move up 63px. So it was the trigger of the main shift. Some other elements in the cluster repeated that upwards shift.

The limitation of only reporting one element means we would need to completely eliminate the first element shift to see the far more significant one.

I agree that we want to avoid reporting on larger elements down the page that result from an element higher up.

Could there be a way to report on the element causing the first significant shift?

**Comment by Tiggerito** [comment]
I tried to work out a way to calculate which element to report on and found out that, in this case, the element causing the problem was in a LayoutShift that was quite small and did not trigger reporting because it was smaller than previous shifts. Its change caused a subsequent LayoutShift which reported on the whole content being pushed down by it. This subsequent shift started with a tiny element that affected nothing, and that is the one reported as the cause.

So a lot trickier than I thought.

**Comment by tunetheweb** [comment]
I say lets keep it as it as the first one. As you rightly point it, it's not possible to precisely identify the root cause of the largest shift and it varies on a case by case bases. Plus all the entries are returned anyway i the `entries` array if you do want to report more.
