### ISSUE TITLE
How to inject web-vitals library function in playwright browsers environment ?

### ISSUE THREAD

**Issue by ferozali690** [GoogleChrome/web-vitals#316]
I am trying to get a web-vitals metrics result from the reportWebVitals function from the web-vitals npm package but unable to achieve the result using playwright, it throws an error saying **"page. evaluate: ReferenceError: _reportWebVitals is not defined"**

```
import type { ReportHandler } from 'web-vitals';

const reportWebVitals = (onPerfEntry?: ReportHandler) => {
  if (onPerfEntry && onPerfEntry instanceof Function) {
    import('web-vitals').then(({ getCLS, getFID, getFCP, getLCP, getTTFB }) => {
      getCLS(onPerfEntry);
      getFID(onPerfEntry);
      getFCP(onPerfEntry);
      getLCP(onPerfEntry);
      getTTFB(onPerfEntry);
    });
  }
};

export default reportWebVitals;

```

```
import reportWebVitals from '../src/reportWebVitals';
import { Browser, chromium, expect, test } from '@playwright/test';
import { Page } from 'playwright';

const HOME_PAGE_URL = 'http://localhost:4000/';

test.only('Performance Checks using web-vitals library', async ({ browser }) => {
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto(HOME_PAGE_URL, { waitUntil: 'networkidle' });
  const getVitals = (args) => {
    console.log('args', args);
    
  };
  await page.evaluate(async () => {
    reportWebVitals(getVitals);
  });
});

```

**Comment by tunetheweb** [comment]
I'm afraid I don't use Playwright and can't really advise but see #180 as one implementation that someone has used (based on an older version of web-vitals) in case that helps.

**Comment by cloudydaiyz** [comment]
Hello from the future! 👋🏾

If anybody is still having trouble with this, I've uploaded [a gist](https://gist.github.com/cloudydaiyz/923ca44bdb0a1ff3434a9360967025a6) with a sample of how to use the library in Playwright browsers.

**Comment by philipwalton** [comment]
@jancbeck I would not recommend that approach. While yes it is simpler, it's also less robust. There are a lot of edge cases the web-vitals library handles that your script does not.

For example:

1. This script does not measure CLS properly [using windows](https://web.dev/blog/evolving-cls)
2. This script will not handle LCP elements that render more than 500ms after the `load` event
3. This script does not account for pages that are prerendered
4. The script will not properly handle pages loaded in the background
5. Etc.

While some of these things are less important in automated testing scenarios, I'd want to make sure anyone using this script is aware of those difference. I wouldn't want someone to just copy this snippet and assume it works the same as this library.

**Comment by philipwalton** [comment]
> For a simple smoke test to detect performance regressions, this is good enough for me.

Yep, I'm all for simple solutions in cases that don't require something more complex. But I did want to make it clear to anyone reading this thread that your example code isn't a drop-in replacement for what the `web-vitals` library measures.
