### ISSUE TITLE
[Feature Request] Add options to onFcp onLcp to ignore specific elements

### ISSUE THREAD

**Issue by Amorites** [GoogleChrome/web-vitals#321]
My company adds a very large, almost transparent image for watermarking on intranet page launch, which affects the calculation of the fcp lcp metric. I hope that some options can be added to circumvent the problem of actually invisible elements being involved in the calculation.

**Comment by tunetheweb** [comment]
Closing this for now, since this is not an request for this library and more a question for what is eligible as LCP element.

You can follow this issue for investigations in this space: https://bugs.chromium.org/p/chromium/issues/detail?id=1288402
