### ISSUE TITLE
`startTime` missing from TS types

### ISSUE THREAD

**Issue by magnattic** [GoogleChrome/web-vitals#322]
I am using web-vitals in my nextjs application like this:

```
import { ReportCallback } from 'web-vitals';

export const reportWebVitals: ReportCallback = (metric) => {
  console.debug(
    'Metric:',
    padEnd(20, metric.name),
    `${padEnd(18, metric.startTime)} + ${metric.value}`,
  );
};
```

Which works perfectly fine during runtime, the output is something like
![image](https://user-images.githubusercontent.com/7560166/221233942-3b12debf-35e4-4aa6-bb59-d733060f649e.png)

However, typescript will complain:
> Property 'startTime' does not exist on type 'Metric'.

Why is `startTime` not part of the typings? Can you maybe add it? 

Or am I abusing some internal variable here and should access this in another way?

**Comment by tunetheweb** [comment]
`startTime` doesn't exist on the `Metric` but only on the `Metric.entries` so not sure how your code above "works" but it shouldn't.

**Comment by magnattic** [comment]
Ah, mystery solved:
While it looks like NextJS simply exposes the regular `reportWebVitals` function, it seems to actually be some kind of wrapper with custom logic and types:
https://nextjs.org/docs/advanced-features/measuring-performance#typescript

Very misleading, they could have picked a slightly different name at least.

![image](https://user-images.githubusercontent.com/7560166/223204931-5da1c261-2403-4b33-88f7-f27ed2972eb1.png)

For anyone stumbling across this in the future, the type to import in this case is `NextWebVitalsMetric`.
