### ISSUE TITLE
attribution typescript error

### ISSUE THREAD

**Issue by oppianmatt** [GoogleChrome/web-vitals#331]
Using the example from the README.md

```
import {onCLS, onFID, onLCP} from 'web-vitals/attribution';

function sendToGoogleAnalytics({name, delta, value, id, attribution}) {
  const eventParams = {
    // Built-in params:
    value: delta, // Use `delta` so the value can be summed.
    // Custom params:
    metric_id: id, // Needed to aggregate events.
    metric_value: value, // Optional.
    metric_delta: delta, // Optional.
  };

  switch (name) {
    case 'CLS':
      eventParams.debug_target = attribution.largestShiftTarget;
      break;
    case 'FID':
      eventParams.debug_target = attribution.eventTarget;
      break;
    case 'LCP':
      eventParams.debug_target = attribution.element;
      break;
  }

  // Assumes the global `gtag()` function exists, see:
  // https://developers.google.com/analytics/devguides/collection/ga4
  gtag('event', name, eventParams);
}

onCLS(sendToGoogleAnalytics);
onFID(sendToGoogleAnalytics);
onLCP(sendToGoogleAnalytics);
```

Generates a typescript error:

```
Argument of type '({ name, delta, value, id, attribution }: { name: any; delta: any; value: any; id: any; attribution: any; }) => void' is not assignable to parameter of type 'CLSReportCallbackWithAttribution'.
  Types of parameters '__0' and 'metric' are incompatible.
    Property 'attribution' is missing in type 'CLSMetric' but required in type '{ name: any; delta: any; value: any; id: any; attribution: any; }'.
```

It seems the function still thinks it's a CLSMetric and not a CLSMetricWithAttribution

**Comment by tunetheweb** [comment]
I can't repeat this. Can you give steps as to how you are seeing this?

**Comment by tunetheweb** [comment]
Oh I can repeat this when adding a file directly to the src directory. You should be importing the built files not the source files.

**Comment by OliverJAsh** [comment]
I'm also running into this problem. Reduced test case:

```ts
import * as WebVitals from 'web-vitals/attribution';
WebVitals.onCLS((x) => {
  /*
  Property 'attribution' does not exist on type 'CLSMetricWithAttribution | CLSMetric | Metric'.
    Property 'attribution' does not exist on type 'CLSMetric'.
  */
  x.attribution;
});
```

The problematic code is here: https://github.com/GoogleChrome/web-vitals/blob/64f133590fcac72c1bc042bf7b4ab729d7e03316/src/types/cls.ts#L86

We need to remove `extends CLSReportCallback`, otherwise TypeScript will create a union of functions. Reduced test case to illustrate this:

```tsx
interface A {
  (x: { a: number }): void;
}
interface B extends A {
  (x: { b: number }): void;
}
const foo: B = (param) => {
  param;
  // { a: number; } | { b: number; }
};
```

**Comment by tunetheweb** [comment]
But `CLSReportCallbackWithAttribution` does extend `CLSReportCallback` - it doesn't redefine all the properties defined in `CLSReportCallback`. Without that `extends` we miss these :

https://github.com/GoogleChrome/web-vitals/blob/64f133590fcac72c1bc042bf7b4ab729d7e03316/src/types/cls.ts#L22-L26

Or we could repeat them in CLSReportCallbackWithAttribution but seems less than ideal.

The below works to remove the error, but not sure if that's the best way of doing this:

```
import {
  onCLS,
  onFCP,
  onFID,
  onLCP,
  onTTFB,
  onINP,
} from 'web-vitals/dist/web-vitals.attribution';
```

**Comment by OliverJAsh** [comment]
> The below works to remove the error:

That doesn't help:

```ts
import { onCLS } from 'web-vitals/attribution';
onCLS((x) => {
  /*
  Property 'attribution' does not exist on type 'CLSMetricWithAttribution | CLSMetric | Metric'.
    Property 'attribution' does not exist on type 'CLSMetric'.
  */
  x.attribution;
});
```

**Comment by OliverJAsh** [comment]
> Without that `extends` we miss these :

I think those properties will still exist, because they come from a different `extends` (`CLSMetricWithAttribution extends CLSMetric`).

**Comment by tunetheweb** [comment]
No that doesn't seem to work as it fails to build:

```
src/attribution/onCLS.ts:42:10 - error TS2352: Conversion of type 'CLSMetric' to type 'CLSMetricWithAttribution' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Property 'attribution' is missing in type 'CLSMetric' but required in type 'CLSMetricWithAttribution'.

42         (metric as CLSMetricWithAttribution).attribution = {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/types/cls.ts:73:3
    73   attribution: CLSAttribution;
         ~~~~~~~~~~~
    'attribution' is declared here.
```

Hmmm not sure what is going on here.

BTW this does work, but seems a little messy:

```js
import { onCLS } from 'web-vitals/dist/web-vitals.attribution';
```

I don't know why this doesn't as it's basically the same thing:

```js
import { onCLS } from 'web-vitals/attribution';
```

**Comment by OliverJAsh** [comment]
> BTW this does work, but seems a little messy:
> 
> ```js
> import { onCLS } from 'web-vitals/dist/web-vitals.attribution';
> ```

That doesn't work for me:

```
Could not find a declaration file for module 'web-vitals/dist/web-vitals.attribution'.
```

I'm testing this in a fresh project.



> No that doesn't seem to work as it fails to build:

On `master`, I applied this patch and `npm run build:ts` completes successfully:

```diff
diff --git a/src/attribution/onCLS.ts b/src/attribution/onCLS.ts
index 0e62a7d..2aa951a 100644
--- a/src/attribution/onCLS.ts
+++ b/src/attribution/onCLS.ts
@@ -83,7 +83,7 @@ export const onCLS = (
   unattributedOnCLS(
     ((metric: CLSMetric) => {
       attributeCLS(metric);
-      onReport(metric);
+      onReport(metric as CLSMetricWithAttribution);
     }) as CLSReportCallback,
     opts
   );
diff --git a/src/types/cls.ts b/src/types/cls.ts
index 58dbce3..11ec632 100644
--- a/src/types/cls.ts
+++ b/src/types/cls.ts
@@ -83,6 +83,6 @@ export interface CLSReportCallback extends ReportCallback {
 /**
  * A CLS-specific version of the ReportCallback function with attribution.
  */
-export interface CLSReportCallbackWithAttribution extends CLSReportCallback {
+export interface CLSReportCallbackWithAttribution {
   (metric: CLSMetricWithAttribution): void;
 }

```

I'm not sure if the type assertion is safe though.

**Comment by tunetheweb** [comment]
#348 seems to fix it in a better way I think. You can test it with: `npm install web-vitals@next`

**Comment by tunetheweb** [comment]
It looks like src/attribution/onCLS.ts specifically had an incorrect type which fixes the `onCLS((x) => { x.attribution; });` issue.

But a bigger fix was also needed for all the metrics for a `onCLS(callAFunction)` call.

**Comment by OliverJAsh** [comment]
Amazing, thank you!

**Comment by OliverJAsh** [comment]
Note: I upgraded to 3.3.2 but I'm still facing type errors. See https://github.com/GoogleChrome/web-vitals/issues/351.

**Comment by cklim4405** [comment]
> Oh I can repeat this when adding a file directly to the src directory. You should be importing the built files not the source files.
