### ISSUE TITLE
Interaction count estimate seems flaky

### ISSUE THREAD

**Issue by josephwynn-sc** [GoogleChrome/web-vitals#333]
Hi team! I don't know if this is a bug report or a question, but I've been playing around with INP and I'm not sure what to make of [the interaction count estimate logic](https://github.com/GoogleChrome/web-vitals/blob/main/src/lib/polyfills/interactionCountPolyfill.ts#L37). In some pages I've looked at, the estimate seems relatively accurate. However I have found a bunch of pages with 200+ interactions where only 1 or 2 interactions have an `interactionId`. This causes the interaction count to be estimated as really small.

On these pages with a high interaction count, it seems like INP is being overestimated because [this logic](https://github.com/GoogleChrome/web-vitals/blob/main/src/onINP.ts#L116-L123) picks the longest INP rather than a high percentile estimate of the 200 interactions. Is this expected? If so, why? Are interactions with no ID considered to be unreliable data or something?

**Comment by tunetheweb** [comment]
Only interactions with an `interactionId` are eligible to be included in the INP calculation (with the small exception that FID interactions are included even if no interactionId). You can see that logic here:

https://github.com/GoogleChrome/web-vitals/blob/fb01e300f8e0589c6ccf3e086568c3813edf1c49/src/onINP.ts#L163-L192

This means if you are only getting 1 or 2 interactions with an interactionId then you only have 1 or 2 (or perhaps three) INP-eligible interactions and on that case yes we do take the longest one. Only for pages with large numbers of interactions do we ignore the extreme outliers.

The following interactions [have an `interactionId`](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEventTiming/interactionId#description):
![interactionId elements](https://user-images.githubusercontent.com/10931297/227457146-0d2a0aa7-9bf0-4664-a74a-419493ff6a23.jpeg)

Which ties in the with events considered for INP as documented here: https://web.dev/inp/#whats-in-an-interaction

There are a [great many other events](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceEventTiming#events_exposed) that INP doesn’t currently consider as an “interaction” and some that also don’t emit an PerformanceEventTiming event (for example scrolling) that also are not considered.

**Comment by josephwynn-sc** [comment]
Thanks for clarifying, @tunetheweb! I'm not sure how I missed that detail about which events are considered for INP.
