### ISSUE TITLE
Playwright : document is not defined

### ISSUE THREAD

**Issue by MehseinJohan** [GoogleChrome/web-vitals#334]
Hello team,

I've installed the framework in my playwright regression. 
Though, when trying to play my script : 

test('screenshot_testing', async ({ cWelcomePage, page, webActions, baseURL, browserName }) => {
  //Display Home page
  await WelcomePage.isPageSuccessfullyDisplayed()
  onCLS(console.log);

I get rejected with -> "ReferenceError: document is not defined".

Could you please help me ?

Thank you,

Regards,

Johan

**Comment by tunetheweb** [comment]
`onCLS` needs to be executed as a JavaScript API.

I don't think this is an issue with this library, but more how you are using playwright.
Found this form a quick Google: https://github.com/microsoft/playwright/issues/15006
