### ISSUE TITLE
Metric Rating Thresholds not included in attribution builds

### ISSUE THREAD

**Issue by yuhui** [GoogleChrome/web-vitals#338]
Actual result: In the attribution builds, none of the Metric Rating Thresholds are included. Tested with `web-vitals.attribution.js`, `web-vitals.attribution.umd.cjs` and `web-vitals.attribution.iife.js`.

Expected result: With the attribution builds, Metric Rating Thresholds should be available as described at https://github.com/GoogleChrome/web-vitals#rating-thresholds

Affected version: 3.3.0

**Comment by tunetheweb** [comment]
Looks like we missed adding them to:
https://github.com/GoogleChrome/web-vitals/blob/main/src/attribution.ts

Will add and prepare a new release but might take a day or two.
