### ISSUE TITLE
why does onCLS return non CLS metrics?

### ISSUE THREAD

**Issue by jantimon** [GoogleChrome/web-vitals#358]
According to the typings `onCLS` can return CLS Metrics or generic Metrics:
![webVitalMetricCollector_ts_—_isomorph](https://github.com/GoogleChrome/web-vitals/assets/4113649/40936f99-f82f-4697-8572-6f331a25ca87)

Is that a typing bug?

**Comment by tunetheweb** [comment]
I can't repeat this, but I think this will be fixed with #356

**Comment by tunetheweb** [comment]
Yeah weirdly I get `any` on 3.3.2:

<img width="205" alt="image" src="https://github.com/GoogleChrome/web-vitals/assets/10931297/b13a2939-c5a1-41b5-8bce-2a321f358e94">

But yeah it looks like #356 does fix this:

<img width="289" alt="image" src="https://github.com/GoogleChrome/web-vitals/assets/10931297/8d0b6d09-9387-4e89-b0c6-3d0225e76cd4">

**Comment by tunetheweb** [comment]
Maybe your IDE is just cleverer than mine (I use VSCode)?

**Comment by jantimon** [comment]
I am using VSCode too - but probably it was just an invalid cache on my side - restarting VSCode fixed my tooltip (using #356)

![typings_cls](https://github.com/GoogleChrome/web-vitals/assets/4113649/2c4d223b-bbea-47c2-84c5-bf2f560b804c)
