### ISSUE TITLE
Dot Image Added to Page

### ISSUE THREAD

**Issue by proyVolt** [GoogleChrome/web-vitals#365]
Hello, I've inherited a site that is using web-vitals (a package I have zero familiarity with) and I've noticed on my and other peoples' sites that use web-vitals an image of a single dot gets added to the page. Am I correct in assuming that web-vitals is the source of that dot image?

If so, how do I stop it from getting inlined into the page as a data source? Or alternately, can I expect the inlined dot's data value (`'data:image/webp;base64,$HASH`) to be permanently fixed across all future builds?

If it's relevant, the site is built with react.

**Comment by tunetheweb** [comment]
No that is not this package. This package is a JavaScript library to measure the Core Web Vital performance metrics and allow sites to send them back to their analytics provider of choice. It does not add any content to a site other than JavaScript to make the measurements.
