### ISSUE TITLE
Why I get LCP less than FCP?

### ISSUE THREAD

**Issue by xiaofud** [GoogleChrome/web-vitals#369]
Javascript code
```javascript
<script type="module">
        import {onCLS, onFID, onLCP, onFCP} from 'https://unpkg.com/web-vitals@3?module';

        onCLS(console.log);
        onFCP(console.log);
        onLCP(console.log);
    </script>
```

console log
<img width="447" alt="LCP less than FCP" src="https://github.com/GoogleChrome/web-vitals/assets/12378280/b91aaeb1-61d1-4f6c-b006-42f948df1c07">

The LCP element is an image and it's `preload`ed.
<img width="846" alt="image" src="https://github.com/GoogleChrome/web-vitals/assets/12378280/6996a688-2b83-49fa-8ca1-70e616684b2b">

My Chrome version: Version 114.0.5735.198 (Official Build) (x86_64)

**Comment by tunetheweb** [comment]
In theory this shouldn't be possible on a single page load. Do you have a URL where this can be reproduced?

**Comment by xiaofud** [comment]
> In theory this shouldn't be possible on a single page load. Do you have a URL where this can be reproduced?

Hello, I can reproduce the issue at `https://www.iq.com/`, using following code snippet in console

```javascript
const observer = new PerformanceObserver((entryList) => {

  for (const entry of entryList.getEntriesByName('first-contentful-paint')) {
    console.log('FCP candidate:', entry.startTime, entry);
  }

  for (const entry of entryList.getEntriesByType("largest-contentful-paint")) {
    console.log('LCP candidate:', entry.startTime, entry);
  }

  for (const entry of entryList.getEntriesByType("first-input")) {
    const delay = entry.processingStart - entry.startTime;
    console.log('FID candidate:', delay, entry);
  }

});

observer.observe({type: 'paint', buffered: true});
observer.observe({type: 'largest-contentful-paint', buffered: true});
observer.observe({type: 'first-input', buffered: true});
```

<img width="766" alt="image" src="https://github.com/GoogleChrome/web-vitals/assets/12378280/5a7a5847-1804-49b5-9d01-264e800156d0">

**Comment by philipwalton** [comment]
This is happening here because the LCP image is loaded cross-origin, so it's full timing information is not available and the API can only expose the `loadTime` value rather than the `renderTime` value.

If you want to enable full timing data for cross-origin images, you can add the [`Timing-Allow-Origin`](https://developer.mozilla.org/docs/Web/HTTP/Headers/Timing-Allow-Origin) to those image responses (assuming you control the config for that server).

See this related issue for more details: https://github.com/GoogleChrome/web-vitals/issues/260#issuecomment-1242766182 for more details

**Comment by xiaofud** [comment]
> This is happening here because the LCP image is loaded cross-origin, so it's full timing information is not available and the API can only expose the `loadTime` value rather than the `renderTime` value.
> 
> If you want to enable full timing data for cross-origin images, you can add the [`Timing-Allow-Origin`](https://developer.mozilla.org/docs/Web/HTTP/Headers/Timing-Allow-Origin) to those image responses (assuming you control the config for that server).
> 
> See this related issue for more details: [#260 (comment)](https://github.com/GoogleChrome/web-vitals/issues/260#issuecomment-1242766182)

Thanks @philipwalton ! After adding Timing-Allow-Origin header using chrome plugin, I get the correct value.
