### ISSUE TITLE
Question: LCP element determination logic when multiple equal-sized images are rendered within the viewport on page load

### ISSUE THREAD

**Issue by kashifshamaz21** [GoogleChrome/web-vitals#376]
**Summary**

Hi folks,

I have an observation to share and ask about whether this is expected behaviour or not:

We have a web-page on which we display a List of images. When this page is audited via Lighthouse, we are observing that in different audit runs, sometimes the very 1st image in the first row of images gets determined as LCP element, and in other runs, the LCP element picked varies between 2nd image, 3rd image and so on.

- All these images are equally sized. 
- Currently, we are preloading the very first image (using `<link rel="reload" />`, so that it gets fetched early during parsing phase, and makes it get rendered faster when browser finds its corresponding <img /> tag in the HTML later.

Questions: 
1. Is this an expected behaviour, that for a page displaying 2 or more equal sized images within the viewport, any of those images could be determined as the LCP element?
2. If the above is true, then do we need to set `fetchPriority="high"` for all the images in the viewport (first row of images) so that whichever of those images gets determined as LCP element, we render them with `high` priority?

Link to the web page where this issue is reproducible:

Case 1:
LCP element detected was 1st image of the 3 images displayed in the viewport:
https://www.carousell.sg/p/deliveroo-delivery-bag-1127373053/

<img width="1437" alt="Screenshot 2023-08-23 at 2 59 58 PM" src="https://github.com/GoogleChrome/web-vitals/assets/6056421/381bf175-a2a7-4ff7-a554-47c4f736a9d0">

Case 2:
LCP element detected was 2nd image of the 3 images displayed in the viewport:
https://www.carousell.sg/certified-used-phone-l/apple-f/iphone-14-pro-128gb-gold-P121318-PV121320-r/
<img width="1430" alt="Screenshot 2023-08-23 at 2 53 57 PM" src="https://github.com/GoogleChrome/web-vitals/assets/6056421/e0ba0f13-fb2f-440c-9695-7d06761b4528">

**Comment by Tiggerito** [comment]
I've experienced the same in the past. It kind of makes sense that if all three images jointly fill the screen, then they would all be the LCP element. But I think the system has to pick one. It would be interesting to know how.

**Comment by Tiggerito** [comment]
That's a good point with caching. It would be even worse when lazy loading is done with JS.

I was recently thinking about trying to compare cached with non-cached experiences. I think the results would be interesting. Not sure how to perform the split in data. First page visits v the rest of a session? Or I guess you could cookie someone? Or is there a way to detect caching is happening?
