### ISSUE TITLE
[question] why are CLS attribution fields optional?

### ISSUE THREAD

**Issue by williazz** [GoogleChrome/web-vitals#381]
All CLS fields are optional in the schema
https://github.com/GoogleChrome/web-vitals/blob/main/src/types/cls.ts#L38-L66

In this logic here to fill in CLS attribution, why might the attribution not exist?
https://github.com/GoogleChrome/web-vitals/blob/main/src/attribution/onCLS.ts#L36-L56

**Comment by philipwalton** [comment]
> In this logic here to fill in CLS attribution, why might the attribution not exist?

Some pages may not have any layout shifts at all, and in those cases these attribution fields will not be set.

**Comment by williazz** [comment]
But are there cases when some, but not all attributions are captured?

**Comment by philipwalton** [comment]
No, if the attribution data is available then all the fields should be set (see [code](https://github.com/GoogleChrome/web-vitals/blob/v3.4.0/src/attribution/onCLS.ts#L42-L49)).

It's possible the `largestShiftTarget` could be undefined, but that would only happen if there was an error determining the element selector (which could happen but would be rare, see [code](https://github.com/GoogleChrome/web-vitals/blob/v3.4.0/src/lib/getSelector.ts#L44-L46)).

**Comment by williazz** [comment]
Got it. I was confused because in these situations, it's sometimes an optional nested object with required fields, as opposed to required object with optional fields. Thank you so much for walking me through that logic! 

```
