### ISSUE TITLE
The threshold values for each indicator are set the same for both desktop and mobile devices. Is this reasonable?

### ISSUE THREAD

**Issue by zengzuo613** [GoogleChrome/web-vitals#399]
According to statistics from the HTTP Archive or CrUX, we can see that the figures for mobile devices are significantly larger than those for desktop devices. So, is it reasonable to set the threshold values for each indicator the same for both desktop and mobile devices in Web Vitals?

[httparchive-dcl](https://httparchive.org/reports/loading-speed#dcl)

![image](https://github.com/GoogleChrome/web-vitals/assets/76633368/77e24f24-4111-4467-8ff5-03e815c95754)

The indicator values for mobile devices are almost twice as large.

**Comment by tunetheweb** [comment]
Hi, you can read more about how the thresholds were defined here: https://web.dev/articles/defining-core-web-vitals-thresholds

In short the thresholds were set based on mobile devices and achievability. There is an argument that we could have stricter thresholds for desktop, and [for Lighthouse the limits are set per device category](https://developer.chrome.com/en/docs/lighthouse/performance/performance-scoring/#desktop) where the device capabilities are more strictly defined through the network and CPU emulation used. For simplicity sake we went with the same thresholds for the field Core Web Vitals where the lines are a little more blurry (many mobile devices are faster than desktop and are used on WiFi networks that may be equal to desktop).

This defines a minimum, achievable  threshold that we believe represents “good” experience regardless of device category.

**Comment by zengzuo613** [comment]
Thank you for your detailed response, but such settings are too lenient for the desktop. All of our desktop sites, including many that were developed years ago and have not yet been optimized, have an LCP P90 value of 1827.441ms and P75 value of 1072.683ms, which are far greater than the 'good' threshold. In fact, we believe there’s still a lot of room for optimization on many pages.

Therefore, we are not using the built-in thresholds of Web Vitals for our PC performance evaluation at the moment, but are making judgments on the server side, referencing the 90th percentile line of Lighthouse.

Should we consider unifying the standard with Lighthouse, and establish two sets of thresholds that reference CRUX data? This would be more consistent with objective facts.

We use both Lighthouse and Web Vitals tools, but the differing standards can cause confusion for ordinary developers.

**Comment by tunetheweb** [comment]
This library does expose the `rating` value in the metric (`good`, `needs-improvement`, `poor`) but this is a relatively recent change (added last year), and this rating can be ignored and you can set your own thresholds for whatever you want based on the metric value if you want more strict values for some segment of your values.

Changing the wider web-vitals program thresholds is more a question for [the web-vitals feedback group](https://groups.google.com/g/web-vitals-feedback) rather than just for this library.

**Comment by zengzuo613** [comment]
ok tks!
