### ISSUE TITLE
GoogleChrome/web-vitals: Essential metrics for a healthy site.

### ISSUE THREAD

**Issue by keanchuanpoh** [GoogleChrome/web-vitals#419]
"import {onCLS, onFID, onLCP} from 'web-vitals/attribution';

function sendToGoogleAnalytics({name, delta, value, id, attribution}) {
  const eventParams = {
    // Built-in params:
    value: delta, // Use `delta` so the value can be summed.
    // Custom params:
    metric_id: id, // Needed to aggregate events.
    metric_value: value, // Optional.
    metric_delta: delta, // Optional.
  };

  switch (name) {
    case 'CLS':
      eventParams.debug_target = attribution.largestShiftTarget;
      break;
    case 'FID':
      eventParams.debug_target = attribution.eventTarget;
      break;
    case 'LCP':
      eventParams.debug_target = attribution.element;
      break;
  }

  // Assumes the global `gtag()` function exists, see:
  // https://developers.google.com/analytics/devguides/collection/ga4
  gtag('event', name, eventParams);
}

onCLS(sendToGoogleAnalytics);
onFID(sendToGoogleAnalytics);
onLCP(sendToGoogleAnalytics);"
 https://github.com/GoogleChrome/web-vitals#:~:text=with%20each%20metric.-,import%20%7BonCLS%2C%20onFID%2C%20onLCP%7D%20from%20%27web%2Dvitals,%3B%0AonFID(sendToGoogleAnalytics)%3B%0AonLCP(sendToGoogleAnalytics)%3B,-Note%3A%20this

**Comment by rviscomi** [comment]
There doesn't appear to be a question/issue here
