### ISSUE TITLE
Capture all metrics contributing to the Lighthouse performance score

### ISSUE THREAD

**Issue by bripkens** [GoogleChrome/web-vitals#42]
Web vitals and especially this library is a great step towards consistent metrics across a variety of tools. Thank you for this!

I am wondering whether this library could be extended to capture all the metrics contributing to the [Lighthouse performance score](https://web.dev/performance-scoring/)? This would help establish a consistent experience/measurements across the whole tooling landscape. Consistent experiences/measurements could improve adoption and this in turn could improve the experience on the web. WDYT?

I realize that these metrics may not fit under the *web vitals* umbrella, but they do fall into a similar category. 

btw.: Thank you for building this library in such a way that it is closure compiler advanced mode compatible :)

**Comment by philipwalton** [comment]
> I am wondering whether this library could be extended to capture all the metrics contributing to the [Lighthouse performance score](https://web.dev/performance-scoring/)?

Lighthouse is a lab measurement tool, and it's optimized for [lab measurement](https://web.dev/user-centric-performance-metrics/#in-the-lab) use-cases. The intention behind the `web-vitals` library was for it to be a [field measurement](https://web.dev/user-centric-performance-metrics/#in-the-field) tool, and as a result it only exposes metrics that are designed for field measurement.

While I understand the desire to have a unified set of metrics for lab and field, the reality is that it's not possible. Some metrics are just better suited for a lab environment (e.g. they require a lot of processing to compute that you wouldn't want to force on users), and some metrics actually cannot be measured in a lab (e.g. they measure user behavior). As a result, both lab and field metrics are needed.

It's great when a metric can be measured in both environments (e.g. LCP), but we don't want to compromise metric quality just to have a unified set between lab and field.

I hope that makes sense.
