### ISSUE TITLE
LCP value setting to 0 intermittently 

### ISSUE THREAD

**Issue by santhoshmp89** [GoogleChrome/web-vitals#428]
I am running into the issue where LCP value getting set to 0 when the startTime of an entry is 0.

I see that especially this logic where lcp value is getting set to 0.
```
const lastEntry = entries[entries.length - 1] as LargestContentfulPaint;
            if (lastEntry) {
                    if (lastEntry.startTime < visibilityWatcher.firstHiddenTime) {
                    metric.value = Math.max(
                        lastEntry.startTime - getActivationStart(),
                        0
                    );
                    metric.entries = [lastEntry];
                    report(false);
                }
            }
```

More explanation:
In one of my client application he has a page it has a video. He has used video element with source element. The issue is that other entries having startTime in thier entry and only this perticular resource entry not having startTime and its getting set the value to 0.

**Comment by philipwalton** [comment]
> I am running into the issue where LCP value getting set to 0 when the startTime of an entry is 0.

The `startTime` value of a `largest-contentful-paint` entry should never be zero, so I'm not 100% sure what situation you're referring to. Can you clarify?

> I see that especially this logic where lcp value is getting set to 0.

That logic assigns an LCP value of 0 in situations where the page was [prerendered](https://developer.chrome.com/docs/web-platform/prerender-pages) and LCP occurred before the page was activated. In these cases LCP is set to 0 because that's what the user experiences (i.e. the page is rendered instantly).

**Comment by santhoshmp89** [comment]
Thanks for the quick reply. 

Below are the dom structure of the resouces which causing the issue.
![image](https://github.com/GoogleChrome/web-vitals/assets/1115498/ebd6086e-2717-40c5-9552-f189b45f1081)

This is the output for the above resource. If you look at the startTime value it is 0.
![image](https://github.com/GoogleChrome/web-vitals/assets/1115498/b8cf4c31-7f21-46b9-9cc9-707bcb84556e)

**Comment by tunetheweb** [comment]
Chrome currently has a bug for cross-site autoplaying videos:
https://issues.chromium.org/issues/40286891

I presume that’s what’s happening here?

**Comment by santhoshmp89** [comment]
It's not a cross-site auto playing actually. Its subdomain resource.

**Comment by tunetheweb** [comment]
Sorry I meant cross-origin (which this is) not cross-site. So still sounds like this.

Do you see the same issue on image LCPs?

**Comment by santhoshmp89** [comment]
No. I am not seeing issue on image LCP's

**Comment by tunetheweb** [comment]
OK definitely seems like this issue then. This is not an issue with the web-vitals reporting library, but with the underlying implementation in Chrome which is tracked in the above bug. So will close this issue for now.
