### ISSUE TITLE
User consent policy

### ISSUE THREAD

**Issue by jackowpp** [GoogleChrome/web-vitals#434]
Our organization maintains robust user privacy policies. Prior to implementing this tool, we seek clarity on your stance regarding user privacy and compliance with the General Data Protection Regulation (GDPR). Could you kindly provide information about your approach to privacy and whether there is a privacy policy for this library that we can review? Are there any steps we should take prior to implementation of this tool regarding user consent?

**Comment by tunetheweb** [comment]
This library is simply a wrapper around some standard Web APIs which implements best practices in using those APIs to gather performance data for sites to do with as they please (report back to an analytics solution, or just log for debugging). The library does not send this data anywhere by default.

Therefore, we do not provide any guidance on any privacy implications or consent necessary when gathering and reporting back the data this library facilitates.
