### ISSUE TITLE
Bug: LCP attribution can include `resourceLoadDelay` attribution timings far greater than the LCP value in cases where `onTTFB` discards the navigation data

### ISSUE THREAD

**Issue by vanderhoop** [GoogleChrome/web-vitals#439]
__Expected behavior:__ the LCP attribution's `resourceLoadDelay` does not exceed the reported LCP value.

__Actual behavior:__ the `resourceLoadDelay` can currently exceed the reported LCP value in cases where `onTTFB` would discard the navigation data as untrustworthy.

___

__Example data from a real page view:__
```es6
const reported = {
  lcp: 2000,
  lcpAttributionResourceLoadDelay: 17653.7,
  // note the discrepancy between onTTFB and lcpAttributionTTFB
  onTTFB: null,
  lcpAttributionTTFB: 3300.3,
  // FWIW, the resource below has a `Timing-Allow-Origin: *` header
  lcpAttributionResourceUrl: "https://lh3.googleusercontent.com/qE-ZWFf6Q8GMIXN8_dCUU118GmoS43Uc8qW4GKTU64PyuLgqnj5QBpSH14W7UJH3OgXqo-5q_MwG5VWOBSdR_yE=h800-c",
  lcpAttributionResourceLoadTime: 0,
  lcpAttributionCallbackPerformanceNowTimestampForDebugging: 2000,
}
```

__Suspicion:__

At the moment, `onTTFB` issues an early return of undefined in a handful of cases:

https://github.com/GoogleChrome/web-vitals/blob/8058a007c9878c2b56c787040d4e8ca282dc203a/src/onTTFB.ts#L80-L86

However, the `resourceLoadDelay` relies on navigation (TTFB) data _without the protections issued above_:

https://github.com/GoogleChrome/web-vitals/blob/8058a007c9878c2b56c787040d4e8ca282dc203a/src/attribution/onLCP.ts#L64

It should be noted that the calculation of `resourceLoadDelay` can end up relying on the navigation entry for both sides of the subtraction seen above due to the derivation of `lcpRequestStart`
https://github.com/GoogleChrome/web-vitals/blob/8058a007c9878c2b56c787040d4e8ca282dc203a/src/attribution/onLCP.ts#L44-L51

Where `activationStart` is https://github.com/GoogleChrome/web-vitals/blob/8058a007c9878c2b56c787040d4e8ca282dc203a/src/attribution/onLCP.ts#L34

__Some initial options that spring to mind:__

1. Apply the guard clause seen in `onTTFB` within `onLCP` attribution such that it discards all LCP data as untrustworthy in these cases
3. Apply the guard clause seen in `onTTFB` within `onLCP` attribution such that only the TTFB-dependent attribution fields are either **a)** discarded or **b)** clamped somehow

**Comment by tunetheweb** [comment]
Nice details (though a replication would of course be better).

Should be fixed in #440
