### ISSUE TITLE
contributing LoAF basesd code that idenifies LoAF, INF and JS long tasks data

### ISSUE THREAD

**Issue by omriariav** [GoogleChrome/web-vitals#444]
Hello everyone,

I am excited to share with you a script that the Taboola Core R&D team (@BarakKalfa) has prepared. 

The script can be accessed at [https://github.com/taboola/LoAF-Finder](https://github.com/taboola/LoAF-Finder).

This script is designed to meet some of the [requirements](https://github.com/GoogleChrome/web-vitals/pull/442) of showing Long Animation Frames (LoAF) data in the web-vitals library. 

It enables local analysis of LoAF entries for web app optimization, filters 'long-animation-frame' entries based on specific keywords, identifies correlated 'long-task' entries for deeper insights, and categorizes the data for easy comparison. Additionally, it can be downloaded as a CSV file.

The script is available under an open-source license and we welcome contributions. We are happy to receive feedback, issues, and PRs.

Best regards,
Omri.

**Comment by gilbertococchi** [comment]
Thanks Omri for sharing your LoAF experimentation with us.

We would be happy to hear how you found LoAF to INP crossreferencing useful and if you can share the approach that made it most useful for your objectives.

Your feedback could be helpful for @tunetheweb and @mmocny that are workin on the LoAF Attribution PR here https://github.com/GoogleChrome/web-vitals/pull/442.
