### ISSUE TITLE
v4 giving undefined TypeError

### ISSUE THREAD

**Issue by ErwinHofmanRV** [GoogleChrome/web-vitals#451]
I ran into this undefined error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'processingStart')
    at web-vitals.attribution.iife.js:1:9784
    at web-vitals.attribution.iife.js:1:10393
    at V (web-vitals.attribution.iife.js:1:3823)
    at web-vitals.attribution.iife.js:1:9712
    at web-vitals.attribution.iife.js:1:1902
    at web-vitals.attribution.iife.js:1:5071
    at HTMLDocument.<anonymous> (web-vitals.attribution.iife.js:1:2125)
```
Screenshot:
![image](https://github.com/GoogleChrome/web-vitals/assets/159031468/2b5d1f16-33d1-432c-b0c9-229e3b78bdfa)

So, this line in the lib:
`a = e.processingStart`
![image](https://github.com/GoogleChrome/web-vitals/assets/159031468/c9ab5b89-1fde-4a4c-86a9-52a9847be8ba)

When testing with this code:

```
(function() {
  var script = document.createElement('script');
  script.src = 'https://unpkg.com/web-vitals@4.0.0-beta.0/dist/web-vitals.attribution.iife.js';
  script.onload = function() {
    Object.keys(webVitals).forEach(function(fn) {
	  fn.indexOf('on') === 0 && webVitals[fn](console.log);
    });
  }
  document.head.appendChild(script);
}());
```

On my own basic site (www.erwinhofman.com) and just clicking somewhere in the window on my white background (I actually didn't had a goal here, but the INP object below shows I clicked on the `h1`).
My goal was to just test if (just like LCP) the TTFB attribution was renamed from `*Time` to `*Duration` as well. 

After switching tabs and returning to the page, I saw the above TypeError (as that's when INP is dispatched). 
No network nor CPU throttling was applied.

FID, FCP & TTFB were all already succesfully logged (as can be seen in the screenshot). 
I also expected INP to be logged, but that never happened because of the above error.

I was able to reproduce it one out of 5 times. Throttling didn't seem to trigger it specifically. 
Might not matter as much, but in all cases, I clicked within the viewport before injecting v4 via my console.
But I do think that me clicking soon in the pageload did matter (web-vitals extension screenshot is showing that an INP was dispatched even before TTFB & FCP).

I also had the web-vitals extension running, which in fact did register an INP. This was its object:
```
{
    "name": "INP",
    "value": 56,
    "rating": "good",
    "delta": 56,
    "entries": [
        {
            "name": "pointerdown",
            "entryType": "first-input",
            "startTime": 902.5,
            "duration": 56,
            "navigationId": "3f7ea673-7a1c-4ddf-88c3-2fa2203dc061",
            "processingStart": 904.6999999880791,
            "processingEnd": 904.6999999880791,
            "cancelable": true
        }
    ],
    "id": "v3-1711894428960-6269522147831",
    "navigationType": "navigate",
    "attribution": {
        "eventTarget": "div.row.row-eq-height>div.col-xs-12.col-lg-6>div.d-flex.align-items-center.h-100>div>h1",
        "eventType": "pointerdown",
        "eventTime": 902.5,
        "eventEntry": {
            "name": "pointerdown",
            "entryType": "first-input",
            "startTime": 902.5,
            "duration": 56,
            "navigationId": "3f7ea673-7a1c-4ddf-88c3-2fa2203dc061",
            "processingStart": 904.6999999880791,
            "processingEnd": 904.6999999880791,
            "cancelable": true
        },
        "loadState": "loading"
    }
}
```

web-vitals extension:
![image](https://github.com/GoogleChrome/web-vitals/assets/159031468/5e3eb846-c3f6-49a8-9c89-25284ceccc83)

**Comment by philipwalton** [comment]
Thanks for the detailed report! I believe this will be fixed once https://github.com/GoogleChrome/web-vitals/pull/452 is merged and released.
