### ISSUE TITLE
INP: Probably a bad measurement metric for web vitals - even with simple HTML structure pages with no CSS will cause bad value. 

### ISSUE THREAD

**Issue by kangw3n** [GoogleChrome/web-vitals#455]
Hi there

I'm currently working with a news publisher company with approx 5 million page view per day. Due to new metric replacing FID by last month, we encountering a failing INP score for approx 650k URL, So we carefully studying each performance score by gathering a real time field data, sending each INP score (using web-vitals.js) to bigQuery for analysis. 

Initially, we focus on 3rd party library like GTM and GPT, which should be the main causes of the problem due to the nature of these library will consuming most of the main thread works, and it turns out an increasing of 3-5% good score if we remove those library in our initial test, which is a great start of the optimization journey.

But as we try to our effort to move forward furthering decrease our score by changing our code, particulary those using setTimeout and event callback. it turn out no significance increase of good value. 

While we take a deep look on interaction and user_agent based on our field data which we collected from our visitors, we found that most of the bad scores comes from a mid-range devices (Like OPPO Reno 8 or Samsung A53).

From the interaction logs, these bad value actually come from an interaction target like a paragraph or a anchor link click, for paragraph, we can determine that visitor actually will scroll and stop or selecting text on those articles, and for the anchor link, it might be cause by GTM click event that trigger INP which common in page analytic standpoint. 

So to move on our research, we find a devices similar to the field data and do some lab environment testing, we consistantly do an interaction test for nearly 100 time per day but get inconsistance value of the INP, which might greater 1000ms in some case and as low as < 50ms in some case too. This make us so frustrated because we can't find a single target or causes that might make INP value goes so wildly. 

After a ton of tries and discussion, we decide to simplify the process of testing, The idea is removing all known issues that will cause INP like 3rd party library, with a simple HTML page, no CSS (or to be exactly just a simple inline styles); a few paragrah of lorem text, which NO interactive JavaScript beside web-vitals.js for PerformanceEventTiming API to work; and what we found was for some devices mid-range device I've mention above, it turn out on some conditions (or ratherly in most of those test), with a simple scrolling and text selection, **WILL TRIGGER INP** score > 200ms, this is definitely not a great metric in our opinion.

So to make it more clearly, here what we do in our test: 

1. Using an OPPO Reno8 Device. (targeted devices in our field data)
2. Navigate to test pages using Chrome v123  (https://udn.com/upf/static/common/inp.html).
3. Simulate Visitor scrolling and stop by selecting a few text and scroll down abit.
4. Repeat Step 3 for 2 times or more to simulate visitor is indeed reading an article.
5. Return to home page of the device. (which trigger a page visibility event that cause INP to calculate)
6. Navigate back to Google Chrome, INP scroll will show on the page.

Most of our test shows a bad INP score, and we do test it on many devices rather then OPPO or Samsung, it turns out it was a same result. So to make it a simple conclusion in our test:

1. Are mid-range devices the main contributor to bad INP scores?
2. Is it appropriate to rely on device capabilities for this metric?
3. Why do even simple text interactions cause bad INP on these devices?

Please give us a feedback if there is a flaws in our test condition, we do appreciate it as we try to our bast to met the criteria of web vitals, as due to our site is deeply rely on a good inp score. Or if there is some differ insight on this case will be great.

Sorry for a long thread here and we think many of our competitor do struggle on these metric recently, and hope we do raise an issuses about the flaw of these metric. 

Thanks.

**Comment by mmocny** [comment]
This question was [posted to the web-vitals-feedback mailing list](https://groups.google.com/g/web-vitals-feedback/c/xdik2OS5CGI/).  Since this is not related to web-vitals library specifically, and is discussing measurement itself, I suggest closing this issue and continuing the discussion there?
