### ISSUE TITLE
Event not being fired or fired with no value

### ISSUE THREAD

**Issue by raphaelfabeni** [GoogleChrome/web-vitals#47]
Hey all! I know you have this note:

_Note: some of these metrics will not report until the user has interacted with the page, switched tabs, or the page starts to unload. If you don't see the values logged to the console immediately, try switching tabs and then switching back._

But I realized that a few times the events are not being fired at all or with no value attached. This is the implementation based on the `console.log` example that you have it.

```js
import { getCLS, getFID, getLCP } from "web-vitals";

const sendToNR = (event, value) => {
  if (window.newrelic) {
    window.newrelic.setCustomAttribute(event, value);
  }
};

const startSiteSpeed = () => {
  getCLS(metric => sendToNR("CLS", metric.value));
  getFID(metric => sendToNR("FID", metric.value));
  getLCP(metric => sendToNR("LCP", metric.value));
};
```
Is there anything wrong here? Also, is there an accurate way to test these metrics? The Google Chrome extension shows really different numbers for the same page.

**Comment by philipwalton** [comment]
I'm not familiar with how reporting in New Relic works, but is it possible that the expression `window.newrelic.setCustomAttribute(event, value);` is running _after_ your New Relic JS code is sending data to its servers? That would certainly explain why you're not seeing values in some cases. (E.g. if New Relic is sending data in the `load` event, but first input happens after load.)

> But I realized that a few times the events are not being fired at all or with no value attached. 

Can you get me an example of what you mean by "no value attached"? Do you mean a value of zero? Do you mean a value of `null` / `undefined`, do you mean the `value` property does not exist on the reported object?

The way the library is built, it might be possible that a zero value is reported (this is common in the case of CLS), but a `null`, `undefined` or non-existent value should never be reported.

> The Google Chrome extension shows really different numbers for the same page.

Again, can you give me an example? And are you talking about a difference in the number being reported to New Relic or the numbers be logged to the console by the `web-vitals` library? If it's the numbers being reported to New Relic then I suspect it's an issue with how you're using their library (see my first paragraph).

**Comment by raphaelfabeni** [comment]
The first item was already fixed! thanks!
Now about the Google Chrome extension, if you load any page at different times you will get quite a few different results.

**Comment by philipwalton** [comment]
> The first item was already fixed! thanks!

Great!

> Now about the Google Chrome extension, if you load any page at different times you will get quite a few different results.

Please file issues with the extension against that repo: https://github.com/GoogleChrome/web-vitals-extension/

**Comment by raphaelfabeni** [comment]
👍
