### ISSUE TITLE
Facing issue while exporting `web-vitals/attribution` using  `browserify`

### ISSUE THREAD

**Issue by Archish27** [GoogleChrome/web-vitals#486]
Unable to build using `browserify` when using

```js
const {
  onCLS,
  onLCP,
  onFID,
  onINP,
  onFCP,
  onTTFB,
} = require("web-vitals/attribution");
```

Getting error while building browserify -
```
./node_modules/.bin/browserify -d  -t [ babelify --presets [ @babel/preset-env ] ] index.js > dist/bundle.js

/home/archish/code/agent-browser/node_modules/web-vitals/attribution.js:18
export * from './dist/web-vitals.attribution.js';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by tunetheweb** [comment]
There's some suggestions here which seem to work from a quick test: https://stackoverflow.com/questions/51023231/npm-browserify-import-and-export-may-appear-only-with-sourcetype-module.

Alternatively you can use `} = require("web-vitals/dist/web-vitals.attribution.iife.js");` or `} = require("web-vitals/dist/web-vitals.attribution.umd.cjs");` in your code.

But ultimately this is a browserify issue and not a web-vitals issue as far as I can tell so closing this.
