### ISSUE TITLE
Option to batch reporting callbacks

### ISSUE THREAD

**Issue by jonatansberg** [GoogleChrome/web-vitals#49]
I'm looking at setting up a simple standalone backend for collecting and visualizing web-vitals metrics. Being able to report all vitals in one go would in theory simplify that quite a lot. Unfortunately the custom analytics endpoint example in the readme will send a request for each tracked metric, which obviously results in a lot of requests if you track all the available metrics. 

After reading though the source, it seems to me that the reporting callbacks will only trigger when there is data and otherwise do nothing. In theory this prevents a naive attempt at batching using `Promise.all` from working reliably. 

Is there a better way of getting the all the tracked vitals in one go? Or is batching them somehow a bad idea?

**Comment by philipwalton** [comment]
> Is there a better way of getting the all the tracked vitals in one go? Or is batching them somehow a bad idea?

It's not necessarily a bad idea, but as you mentioned it can get tricky because the callback won't necessarily always fire on every page load.

If you want to batch network requests, I'd recommend creating a queue and adding metrics to it any time a callback is called. Then you can add a `visibilitychange` listener to the document, and any time the page's visibility state changes to hidden, send all the metrics in the queue.

Does that make sense?

**Comment by alekseykulikov** [comment]
Check [web-vitals-reporter](https://github.com/treosh/web-vitals-reporter). It's a tiny (800 B) utility library that collects web vitals with one request, adds device information, and handles edge cases.

Example:

```js
import { getCLS, getFID, getLCP } from 'web-vitals'
import { createApiReporter, getDeviceInfo } from 'web-vitals-reporter'

// Init report callback with information about the browser.
const sendToAnalytics = createApiReporter('/analytics', { initial: getDeviceInfo() })

// Setup web-vitals 
getLCP(sendToAnalytics)
getFID(sendToAnalytics)
getCLS(sendToAnalytics)

// Receive `POST /analytics` at the end of the session:
{
  id: '1591874402350-8969370227936',
  cpus: 8, 
  memory: 8, 
  connection: {rtt: 100, downlink: 5, effectiveType: '4g'},
  LCP: 1487, 
  FID: 6, 
  CLS: 1.5602,
  duration: 4560 // session duration
}
```

**Comment by philipwalton** [comment]
I'm going to close this as I think it makes the most sense to leave reporting options up to the developer. Also, as @alekseykulikov points out, there are existing solutions to handle this.
