### ISSUE TITLE
Data Visualization - Can you provide examples/instructions?

### ISSUE THREAD

**Issue by cb-eli** [GoogleChrome/web-vitals#51]
Hello,

I started collecting Web Vitals in my Google Analytics account (using this library).
But, I have no idea how to visualize the data in order to achive a similar report as in 'Google Search Console', 'Chrome UX Dashboard' or anything basic.

It would be great if you could provide some examples/instructions.

It would be really great if you could create a DataStudio template to visualize the web vitals events in Google Analytics.
I guess this is the most common use-case and will make the many users' life easier.

Thanks!

**Comment by philipwalton** [comment]
> It would be really great if you could create a DataStudio template to visualize the web vitals events in Google Analytics.

Thanks for the suggestion, we're actually planning to do this in the near future because we know it's not clear how best to get this data out of Google Analytics.

**Comment by dryoma** [comment]
Yeah, that would be great.

**Comment by robflaherty** [comment]
In case anyone finds it helpful I posted a Python script I've been using to extract Web Vitals events out of GA. It prints out percentiles and distributions. Charting is up to you 😀 
https://github.com/robflaherty/web-vitals-reports

**Comment by KarnaVay** [comment]
And maybe you`ll find helpful more simple way - to visualize it. 
If you use gtm implementation: 

Just create such variable 
`function () {
    var eventValue = {{eventValue}};
  if(eventValue < 2500) {
    return "Good LCP";  
  }
  if(eventValue > 4000) {
    return "Poor LCP";  
  }
  return "NI LCP";
}`

And change your tag in such way: 
https://www.screencast.com/t/AhjBWjWK

And you`ll receive events with labels: Good, Poor, NI. So you can visualize it in data studio, or check numbers in GA

**Comment by philipwalton** [comment]
Sorry it took longer than expected, but a visualization tool for using the web-vitals library with Google Analytics is available here: https://github.com/GoogleChromeLabs/web-vitals-report
