### ISSUE TITLE
INP attribution helper latestProcessingEnd never initialized

### ISSUE THREAD

**Issue by rviscomi** [GoogleChrome/web-vitals#510]
[`latestProcessingEnd`](https://github.com/GoogleChrome/web-vitals/blob/5b91b766031c435e44dda912be75f685d77fe073/src/attribution/onINP.ts#L66) is declared without a value, so it's initially undefined.

When [comparing](https://github.com/GoogleChrome/web-vitals/blob/5b91b766031c435e44dda912be75f685d77fe073/src/attribution/onINP.ts#L116) the undefined value with `entry.processingEnd`, the result is always `NaN`.

And finally, when the `NaN` value is [compared](https://github.com/GoogleChrome/web-vitals/blob/5b91b766031c435e44dda912be75f685d77fe073/src/attribution/onINP.ts#L207) with `loaf.startTime` the result is always false, so the LoAF entries are always kept.

**Comment by brendankenny** [comment]
> so the LoAF entries are always kept

one bit of good news is that this at least maxes out at `MAX_PREVIOUS_FRAMES`, so we don't keep more than 50 + 10 (if the 10 longest LoAFs aren't in the most recent 50), but yeah
