### ISSUE TITLE
Any way to simulate clicks for INP testing?

### ISSUE THREAD

**Issue by hakunin** [GoogleChrome/web-vitals#513]
Hi,
I am testing a page where I want to click a few buttons and get the score.

I have `{ reportAllChanges: true }` and I can trigger INP reporting manually by interacting with the page, but not with JS.

Is there a way to explicitly trigger web vitals so I can measure the score?

**Comment by mmocny** [comment]
The Event Timing API will not report any events which are dispatched synthetically from js, say via `dispatchEvent` calls or `.click()` calls.  So, web-vitals.js will not be able to measure any of these (as they are not user interactions).

If you do want to synthetically test a site, you have to find a way to automate "real" interactions with the browser using browser automation tools (like WebDriver, [Puppeteer](https://pptr.dev/), or Web Platform Tests), or [directly from Chrome Dev Tools you can use the Recorder tool](https://developer.chrome.com/docs/devtools/recorder).

**Comment by hakunin** [comment]
Gotcha, too bad that makes simple quick testing impossible.

**Comment by mmocny** [comment]
Automating the browser with puppeteer is actually surprisingly easy, and offers a nice js api (like you ask for).  You don't even need to do that-- you can literally just hit "record", interact manually with the page, then later just "replay" that recording with the Recorder tool.

Is there something that you are looking for that isn't solved by the above?  I think it just takes an hour to learn and will be a tool for your toolbelt (imho).

---

Here's what I just did to get running on a new machine:

* Create a new directory, and `npm init -y` into it
* Install puppeteer: `npm i puppeteer-core`
* Create this file, then run it:

```js
const puppeteer = require('puppeteer-core');

(async () => {
  const browser = await puppeteer.launch({
    executablePath: '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',
    headless: false
  });

  const page = await browser.newPage();
  await page.goto('https://inp-demo.glitch.me', { waitUntil: 'networkidle0' });

  // First, set up the page.
  // Set all sliders to the midway mark
  await page.evaluate(() => {
    const sliders = document.querySelectorAll('input[type="range"]');
    sliders.forEach(slider => {
      slider.value = (slider.max - slider.min) / 2;
    });
  });


  // Simulate Real Interactions!
  const selector = "textarea";
  await page.click(selector);
  await page.type(selector, "This is some text");

  // Get the INP value, after interactions
  // It would be better to inject this earlier and not rely on buffered, but this is easier. 
  const inpValue = await page.evaluate(async () => {
    // Wait for a brief moment to ensure all interactions are processed
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Calculate INP value
    let largestEventDuration = 0;
    new PerformanceObserver((entryList) => {
      const entries = entryList.getEntries();
      for (const entry of entries) {
	if (!entry.interactionId) continue;
        largestEventDuration = Math.max(largestEventDuration, entry.duration);
      }
    }).observe({ type: 'event', buffered: true });

    // Wait for another brief moment to ensure INP calculation is settled.
    // Would also be better to ensure all the specific interactions are done...
    await new Promise(resolve => setTimeout(resolve, 1000));

    return largestEventDuration;
  });

  console.log(`INP value: ${inpValue}`); // Output the INP value

  await browser.close();
})();

```
