### ISSUE TITLE
Implementation problems

### ISSUE THREAD

**Issue by nclapp** [GoogleChrome/web-vitals#53]
Hello - We are implementing Web Vitals via GTM following the documentation here, but it does not seem to be working as expected. The tag fires on gtm.js and loads the library, but the actual metrics don't seem to be set on DOM ready. When we call them, some are defined, some are undefined. Does this in fact need to be hard-coded for the timing to work correctly? Are we missing something? Thanks in advance! ~Natty C.

**Comment by philipwalton** [comment]
The metrics are not expected to be available on DOMReady. Consider the fact that first input often happens well after the DOM is ready, and the largest image is almost always downloaded after the DOM is ready as well. For CLS, it measure layout shift during the entire lifecycle of the page, so it will never be available by DOMReady.

**Comment by nclapp** [comment]
Thanks for responding. We were wondering how that would be possible, but were just looking at the 'DOMContentLoaded' listener while implementing https://github.com/GoogleChrome/web-vitals#load-web-vitals-from-a-cdn in a GTM tag and thinking that was the same.

I guess the question is, can we implement this through GTM, or not? It's clearly not working as we have it now.

Thanks!

**Comment by philipwalton** [comment]
@nclapp were you able to get this working?

As far as I know, it's possible to use this library with GTM (I've heard of a few people successfully doing it), but I'm not a GTM user myself, so unfortunately I can't really help in that regard.

**Comment by dryoma** [comment]
We've been able to successfully send the stats to GTM. If the setup in GTM is correct - and it might be quite tedious to do it right! - you might need to check that `dataLayer` is not reassigned/overwritten somewhere later in the code.

**Comment by nclapp** [comment]
Thanks for all your help on this. We were able to resolve using documentation we found at https://www.tagmanageritalia.it/advanced-guide-how-to-track-core-web-vitals-with-google-tag-manager/.
