### ISSUE TITLE
v5 browser support tradeoff is problematic for RUM scripts

### ISSUE THREAD

**Issue by sgomes** [GoogleChrome/web-vitals#545]
Hey folks! 👋

We're currently building the next version of our RUM script on top of `web-vitals`, in order to ensure that our handling of CWV metrics is as consistent as possible with CrUX's. CWV metrics aren't the only thing our script collects, but are obviously an important part of it.

We have two main priorities with our RUM script: keeping it as small as possible, to avoid interfering with page performance; and having it work in as many browsers as possible, so that at the very least we have an awareness of the prevalence of older browsers, even if the data we collect on those is limited.

In order to do this, we transpile to older syntax, which works quite well with `web-vitals` v4. If we upgrade to the v5 RC, however, our bundle size increases by approximately one quarter. The main reason behind the size increase appears to be helpers for new syntax such as `for ... of` and object spreads, which was added in #525 to take advantage of the reduced browser support, even though the prior code worked correctly.

I don't think our script is alone in trying to gather data from as many browsers as possible; having browsers in which your script breaks means having no awareness of those visits, which is an issue when trying to get a global picture of your audience. Furthermore, the size benefits of switching to the reduced browser support are fairly limited: per `bundlephobia`, [v4.2.3 is about 2.6KB](https://bundlephobia.com/package/web-vitals@4.2.3), whereas the [v5 RC is 2.2KB](https://bundlephobia.com/package/web-vitals@5.0.0-rc.0);  indeed smaller, but by only around 400 bytes or 15% (at least some of which may be due to other changes anyway, such as dropping FID). Don't get me wrong: it's a nice savings! But unfortunately dependants that need ES5 are left with a 1KB *increase*, rather than a 0.4KB decrease. And as far as I'm aware, things could get significantly worse still if syntax like `async` / `await` ever makes its way into the codebase.

As such, since we don't want to lose visibility on older browsers, our only options are to accept the bundle size increase (and the risk of it becoming even larger over time); or alternatively to fork and maintain a parallel `web-vitals` internally.

Would it be possible to reconsider the browser support decision?

**Comment by philipwalton** [comment]
Hey Sergio! 👋

Can you talk a bit more about what specific performance data your script is collecting from ES5-only browsers? None of the Core Web Vitals metrics are supported in any ES5-only browser, and the only metric exposed by the `web-vitals` library that is supported is TTFB, which we see as primarily valuable as a diagnostic of LCP.

> I don't think our script is alone in trying to gather data from as many browsers as possible; having browsers in which your script breaks means having no awareness of those visits, which is an issue when trying to get a global picture of your audience.

I get the motivation to collect usage data from as many visitors as possible. I don't think that's the same use case as wanting to collect performance-specific data, in order to improve the experience for those users. I don't believe it's critical (nor is it possible) to do that for all users, which is why even in the initial release of `web-vitals` we recommended that folks load it using `<script type="module">`, to avoid requiring older browsers to download a script that couldn't really benefit those users.

I understand that if you want to bundle the `web-vitals` library into another analytics script you're serving—and you want _that_ script to be able to run in ES5-only browsers—then that will require the entire script to be downleveled to ES5 syntax, which can incur a size penalty.

However, I'm sure you know that there are ways for site owners to mitigate that cost by conditionally serving only the ES5 syntax to ES5 browsers—and that's the approach recommend.

You could also potentially dynamically import the `web-vitals` script in a try/catch and only invoke the `onXXX()` functions if the load succeeds. That way you're reducing the total script load for those users.

> Would it be possible to reconsider the browser support decision?

My position (as I've [written about recently](https://philipwalton.com/articles/the-state-of-es5-on-the-web/)) is that it should be up to site owners to make browser support decision, rather than JavaScript library authors. I fully acknowledge your specific desire to support ES5 browsers, but this is not something that all site owners need, and we do not want to impose additional, unnecessary code on users who do not need it.

Of course there are trade offs here, but we believe it's in the best interest of the web ecosystem to keep pushing forward, and we don't think we're pushing too early.

**Comment by sgomes** [comment]
> Can you talk a bit more about what specific performance data your script is collecting from ES5-only browsers? None of the Core Web Vitals metrics are supported in any ES5-only browser, and the only metric exposed by the `web-vitals` library that is supported is TTFB, which we see as primarily valuable as a diagnostic of LCP.

Of course, happy to provide some more details!

Our goal is to have a single, small script that collects various kinds of performance data, together with other data such as UA string and URL path, as well as other service-level info, in order to enable aggregating performance data in various useful ways.

The data includes:
- CWV metrics (including the `web-vitals`-reported TTFB)
- Navigating Timing metrics
- A boolean indicating whether the page was served from our edge cache
- A boolean indicating whether the visitor was signed in (relevant because of caching concerns)
- ECT, downlink, and estimated RTT
- Origin and path
- Which of our "providers", and which of our "services" served the request (to distinguish between different systems and sub-systems)

ES5-only browsers are generally only expected to report the Navigation Timing data, which is useful on its own for network and server performance analysis; but even if they didn't, just having an awareness of these page visits, as well as the URL, origin, and system that they're hitting, is incredibly helpful in getting an idea of what we *don't* know. Having a conspicuous hole in the performance data is valuable in and of itself, so we need a mechanism to make that hole as visible and measurable as possible.

> I get the motivation to collect usage data from as many visitors as possible. I don't think that's the same use case as wanting to collect performance-specific data, in order to improve the experience for those users.

I wasn't too clear above, so I apologise for the misunderstanding. The data we're collecting is all performance-focused, consisting of either performance metrics or other markers that help us aggregate that performance data in different ways. This system doesn't handle general analytics aspects at all.

It's certainly possible to split the data collection into two scripts (or one script and one server-side logger), but that means either dropping the service-level data and losing the ability to aggregate in that way; or alternatively, duplicating that data collection between the two systems and finding mechanisms for cross-referencing the data across both systems to avoid duplicates.

Having a single, standalone script is incredibly simpler and has been a fairly robust approach so far, which is why we're inclined to continue pursuing it.

> I don't believe it's critical (nor is it possible) to do that for all users

The main goal isn't to gather all performance data for all users; we know that's impossible, so we try to get just as much as is possible. It's better to know TTFB, Navigation Timing info, and whether the request hit the edge cache, than to know nothing at all — or worse, to be unaware of the visit.

And for that, the main thing we need to ensure is that the script does not fail during parsing. As I'm sure you're aware, it's impossible to defend against unsupported syntax, since parsing happens before execution; which means short of using `eval` and potentially causing CSP violations, there's no way for a script to guard against its own syntax being unsupported.

> which is why even in the initial release of `web-vitals` we recommended that folks load it using `<script type="module">`, to avoid requiring older browsers to download a script that couldn't really benefit those users.

There are a few issues with using this approach for differential script loading.

First of all, module scripts come with additional restrictions, particularly around cross-origin concerns. Using a module script would mean moving to serving them in-origin, or alternatively setting up CORS headers for the common origin that currently serves them. Not an insurmountable challenge by any means, but a difficult one to justify on an otherwise working system.

But more importantly, the `module` / `nomodule` approach to differential builds is fixed to a particular point in time, which grows increasingly irrelevant as time goes by. It would certainly solve the ES5 issue, yes, but as more and more supported syntax makes its way into the Baseline Widely Available profile and inevitably `web-vitals`, so too would more and more syntax need to be transpiled to match the `module` support line in the sand — which I believe is already approximately 4 years old?

Which means that while it would mostly solve our issue now, we would likely end up with similar issues soon enough, given that our transpilation would by necessity be fixed to an immutable profile, while `web-vital`'s would be a moving target in a constantly evolving platform.

> I understand that if you want to bundle the `web-vitals` library into another analytics script you're serving—and you want _that_ script to be able to run in ES5-only browsers—then that will require the entire script to be downleveled to ES5 syntax, which can incur a size penalty.

Again, I wouldn't call it an analytics script; it's entirely performance-focused. Sorry for the confusion. Other than that, yes, that is a correct summary.

> However, I'm sure you know that there are ways for site owners to mitigate that cost by conditionally serving only the ES5 syntax to ES5 browsers—and that's the approach recommend.

Unfortunately, in our experience there aren't any good primitives on the web for client-side differential script loading.

I'm sure we agree that the server-side UA-based approaches are fundamentally flawed, so I won't go into detail there.

As for client-side, the `module` / `nomodule` approach has the issues I mentioned above.

Other approaches are theoretically possible, but extremely high-maintenance in practice. We could, for example, have a build that matches `web-vitals`'s browser support (Baseline Widely Available), and another one for older browsers than that. In theory, we'd have a preliminary script that checks whether the browser supports Baseline Widely Available, and depending on the result of that check dynamically loads the appropriate script.

However, what exactly would that check be? We can't check for syntax because of the aforementioned reasons (unsupported syntax fails during parsing, and eval often runs afoul of CSP), so we'd need to look for web features that correlate to syntax support instead (e.g. whether something like `Array.prototype.flatMap` is present). This would mean handcrafting new checks whenever new syntax makes its way into the Baseline Widely Available (or at least into `web-vitals`), bearing in mind that different browsers adopt new syntax at different times and in different orders.

> You could also potentially dynamically import the `web-vitals` script in a try/catch and only invoke the `onXXX()` functions if the load succeeds. That way you're reducing the total script load for those users.

There are two mechanisms that you could be referring to here: either real, browser-level dynamic import; or a more classic dynamic import that's implemented through some sort of bundler-provided or custom-coded helper. I'll cover both, since I don't know which one you were referring to.

For the former (real browser import), a `try/catch` could work as a mechanism for statically identifying browsers without dynamic import support, since in theory they'll complain about `import` being undefined (even though `import` is a syntax construct, not an actual function, but of course they don't know that). I'd have to double-check, but I'd expect it to work, yes. However, it wouldn't work as the actual loading mechanism because of the cross-origin concerns I mentioned before. Additionally, a separate mechanism (such as transpilation) would be needed to handle any syntax that falls between dynamic `import()` support and Baseline Widely Available anyway — a gulf that again, will only grow over time.

As for the latter ("fake" dynamic import via helpers), it would be worth testing. It would have to be callback-based, of course, not a static try-catch, but assuming that the script's `error` handler is fired and makes its way to a callback somehow (even in a cross-origin context), it could serve as a signal to try loading the other script instead. I'm concerned about the potential fragility, and whether the build system can successfully be massaged to produce such a configuration, but it's worth a try if there are no better options.

> My position (as I've [written about recently](https://philipwalton.com/articles/the-state-of-es5-on-the-web/)) is that it should be up to site owners to make browser support decision, rather than JavaScript library authors. I fully acknowledge your specific desire to support ES5 browsers, but this is not something that all site owners need
> 
> Of course there are trade offs here, but we believe it's in the best interest of the web ecosystem to keep pushing forward, and we don't think we're pushing too early.

I would agree in principle if we had a differential loading mechanism to match this, but the unfortunate reality is that we don't.

Even in a same-origin scenario, `module` / `nomodule` is only useful to decide between two sides of an immutable, arbitrary line in the sand that only grows more distant and irrelevant as time goes by. So while the argument can be made for `module` / `nomodule` being sufficient for ES5 vs ES2015, that reasoning cannot be extended to any later thresholds, particularly moving ones.

"Baseline Widely Available" is a build-time concept that to my knowledge has no feasible runtime differential loading mechanism other than "try loading the modern script and if it fails, load the other one" 😕

> we do not want to impose additional, unnecessary code on users who do not need it.

Supporting easy transpilation to ES5 does not mean having additional, unnecessary code; just a different coding approach in the library. The only reason why the v5 RC requires additional transpilation helpers when compared to v4 is that existing, working code was replaced with newer syntax (such as `for ... of`) that essentially does the same thing.

It should be possible to keep building `web-vitals` in a similar way as before, i.e., in a way that would result in minimal helpers being needed when transpiling — ES5 is valid ES2015+, after all!

Believe me, I do understand the desire to adopt simpler, terser, and in many ways clearer syntax, and not being stuck to a minimum common denominator forever! However, using newer syntax is not an inevitability, and in some cases it makes sense to put in the effort so that transpilation is minimal (e.g. `const` or `let`), rather than verbose (`for ... of`), or incredibly verbose (`async` / `await`).

In our RUM script, that choice seems obvious for all of the aforementioned reasons. We imagine we're not alone in this, and that it would be beneficial to `web-vitals` to easily enable these use-cases without differential loading workarounds, but perhaps we're extrapolating our needs too much? 🙂

**Comment by sgomes** [comment]
Follow-up: as an experiment, I pulled `web-vitals` v5 into our source tree, and modified it to avoid needing large transpilation helpers. At least in our case (we don't use all of `web-vitals`, e.g. attribution), and at least for now, the only changes that were required were moving from `for ... of` back to `.forEach`, and from object spreads back to `Object.assign`.

With those changes in place, the bundle size is effectively identical to using v4, at only 40 bytes difference.

**Comment by philipwalton** [comment]
Glad to hear you found have a workable solution!

For some additional context, the switch to using Baseline Widely Available is part of a larger change that we're standardizing on for all open source projects within Chrome, so we're unlikely to make an exception here just for `web-vitals`.

While I totally understand the arguments you're making in your reply (and why it would be easier for you if `web-vitals` continued to support ES5), ultimately we think the question of browser support should be a decision that individual sites make, as they're the ones who have the most information about their user base.

**Comment by sgomes** [comment]
It's unfortunate we'll have to maintain a fork just to replace the usage of some transpilation-heavy syntactic sugar, but I understand the reasoning behind your approach. Thank you for considering the request!

**Comment by sgomes** [comment]
Thank you for your testing, @tunetheweb, that's really useful info!

> Hi @sgomes , Just to let you know I did some more testing on this that might be of interest to you.
> 
> For a start for `for...of` seems to be [very well supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#browser_compatibility). The latest browsers to support this to seem to be Edge 12 ands Samsung Internet in 2015. So maybe it's not as important to polyfill that?

Yes, support is indeed very good, with IE and 10-year-old versions of modern browsers as the only things left without support. [According to caniuse](https://caniuse.com/mdn-javascript_statements_for_of), this means that nearly 98% of tracked users use browsers that support this.

That said, in order to collect this sort of data (which we would like to, for each site we host), we need to be very conservative. A script that fails when parsing won't beacon, which means we're not aware of that visit, and so users of older browsers would become invisible.

Granted, we need to draw the line somewhere — we won't be supporting ES3, after all! So `for..of` support could potentially be the line in the sand, yes, assuming no other blockers.

> The most recent syntax we have used that is maybe less well supported is `Array.prototype.at` [which only gained Safari support in 2022](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#browser_compatibility), however testing it on older Safari browsers this is not an issue, as they also don't support the metrics that use that syntax (FCP, LCP, CLS, and INP) and testing proves it doesn't stop importing and compiling the bundle for those browsers so this is a non-issue for Safari browsers.
> 
> Chrome 60-92 (released July 2021) does support FCP, but not `Array.prototype.at` which will cause a runtime error when that callback is fired for those browsers, but the rest of the module will continue to run fine, so yes you will miss out on those metrics for those browsers, and you will see errors in console (and any monitoring that collects those errors) but, all in all, I expect those browsers to be rarely used nowadays.

Right, we're not as concerned with things like `Array.prototype.at`, because as you mention it's easy to polyfill without large helpers. And since it's not new syntax, but rather new methods, it won't break when parsing anyway. Which means that we wouldn't have to account for it in `web-vitals`, if we don't expect the library to ever reach those codepaths in older browsers anyway.

> 
> This leaves [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility) and [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing#browser_compatibility) as the main changes that may cause problems on older browsers (< March 2020) but those are less expensive to transpile if support is really needed for them. It is our opinion that support by default is not needed for those, but we're sure some developers will have use cases that diffs from that.

Yes, optional chaining and nullish coalescing are generally not a problem at all. I don't think I've ever seen a helper for any of them; they just generate a little bit of extra inline syntax.

However, object spreads (`{ ... foo }`) also need some largeish helpers, and a few were added in v5 to replace usage of `Object.assign`.

> 
> So the situation may not be as bad as first assumed, and why we are comfortable making this decision. That is not to say we won't use any of this new syntax on metrics that may be supported by older browsers in the future (like TTFB)—and I take your point that the only way to be certain here is to transpile syntax just in case any unsupported syntax used—but I thought you might find these findings interesting.

They are, yes, thank you!

I guess my concern is partly current and partly forward-looking, since Baseline Widely Available will keep moving forward, and already includes syntax that requires some substantially larger helpers if it ever lands in `web-vitals`, such as `async` / `await`.

So, effectively, the only way to guarantee we wouldn't end up with large transpilation helpers without maintaining a fork of `web-vitals` would be to adopt Baseline Widely Available ourselves, which is a much smaller set of users than we'd like when considering e.g. users stuck on Chrome 109 due to dropped OS support.

**Comment by tunetheweb** [comment]
Oh good point about spread operators, but again [this looks to have very good support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#browser_compatibility).

I totally get your concerns, but as you say a line should be drawn somewhere and good to know there is agreement on that, even if there is not exact agreement on where that line should be drawn! And yes the aim is to have this line continually move forward as usage does too which will certainly mean losing support of older browsers on a continual basis (though for our use case, it's questionable whether the metrics collected from them are that useful since they lack bug fixes and improvements to those metrics).

For your fully use case (outside of just these specific web performance metrics), I wonder if this needs some sort if different thinking here to support the (small) subset of older browsers to still allow knowing about them, but without holding back the newer browsers. For example:
- A lighter script for very basic beaconing (which then maybe loads the fully script and allows that to fail in some browsers)? - Or server side logging of an image pixel, for that?

Anyway, will let you ponder that. Good discussion.

**Comment by sgomes** [comment]
> Anyway, will let you ponder that. Good discussion.

Indeed, thank you for continuing the discussion!

Ultimately, for us, I think it comes down to whether it's easier to keep a single-script architecture while maintaining a fork of `web-vitals`; or whether it's better instead to create a two-tier reporting architecture, either with two scripts, or a script + a pixel, as you mention.

There's also the fact that this is a script we're adding to client sites, so we'd rather avoid it failing in the first place. We'd prefer it not to not appear as a potential source of problems, and accidentally mislead anyone debugging a legitimate issue. That again comes down to usage numbers.

For now, at least, it seems that maintaining an internal fork is easier, by staying on top of new `web-vitals` releases and porting changes over. Perhaps one day we'll be forced to reconsider 🙂
