### ISSUE TITLE
FID polyfill is flawed (on desktop)

### ISSUE THREAD

**Issue by mmocny** [GoogleChrome/web-vitals#564]
The FID polyfill will do the following, more or less:

- Register a [set of event listeners for specific types](https://github.com/GoogleChrome/web-vitals/blob/main/src/lib/polyfills/firstInputPolyfill.ts#L172)
  - The first one to fire [becomes the FID event](https://github.com/GoogleChrome/web-vitals/blob/main/src/lib/polyfills/firstInputPolyfill.ts#L56-L65)
- However, if [pointerdown is specifically received first](https://github.com/GoogleChrome/web-vitals/blob/main/src/lib/polyfills/firstInputPolyfill.ts#L159-L163):
  - we first wait for `pointerup` or `pointercancel` event to fire

The problem is, before `pointerup` can fire, if we observe any of the other events, we will resolve the FID timing and clean up, leaving the `pointerdown` FID data hanging.

Well, `mousedown` is often automatically generated inside the `pointerdown` event, and so is guarenteed to fire before `pointerup`.  (On touch devices `mousedown` comes after `pointerup`)

And, any time `pointerdown` has little input delay, but might have some event processing, we will not just pick the wrong event, but also report a large FID value when it might have been small.

---

Example, inject this onto a page before interacting:

```js
function block(ms) {
  const target = performance.now() + ms;
  while (performance.now() < target);
}

['pointerdown', 'pointerup', 'pointercancel', 'mousedown'].forEach(type => {
  document.body.addEventListener(type, (event) => {
    const start = performance.now();
    console.log('Event:', type, "InputDelay:", start - event.timeStamp);

    block(100);
    
    const end = performance.now();
    console.log('Event:', type, "ProcessingTime:", end - start);

    requestAnimationFrame(() => {
        setTimeout(() => {
            const paintEnd = performance.now();
            console.log('Event:', type, 'ToNextPaint(ish)', paintEnd - end);
        });
    });
  });
});
```

Now, inject the FID polyfill.  (I just paste a compiled version into console)

Compare entry event type and value to the real PO value (if you have one).

---

Note: we use the polyfill for bfcache activations.

Two options I see to resolve this:
- Stop measuring other events after we have pointerdown.
  - If you get pointercancel, just reset the polyfill
  - It is probably impossible for real input to sneak in between pointerdown and cancel (on mobile)
- Add a second buffer for non-pointerdown events, which is used only while pointerdown is active
  - If you hit pointercancel, report the other value

**Comment by philipwalton** [comment]
> FID polyfill is flawed (on desktop)

Interesting...BTW, you can blame Tim Dresser for this, he [originally wrote](https://github.com/GoogleChromeLabs/first-input-delay/blob/eb72c59edde3f30533b4c8510bfcb325f7e7c822/first-input-delay.js) this logic :)

> Two options I see to resolve this:

We've removed `onFID()` entirely (including the polyfill) in v5, so I think we've actually already done option 3, which is to just stop using this code altogether—unless I'm missing something?

**Comment by mmocny** [comment]
Oh I thought it was used for non fid reasons, like first event timing event.

Mostly the motivation here was platforms that don't support event timing,
though.

Cheers.
