### ISSUE TITLE
Problem with speed of rendering and when scrolling when displaying multiple photos

### ISSUE THREAD

**Issue by IzatIT** [GoogleChrome/web-vitals#569]
My site has a form for choosing photos, after choosing all the photos should appear below. This is good, but when I choose a lot of photos, for example more than 15-20 good quality ones, Chrome freezes and renders for a long time, scrolling through the photo section slows down a lot, just like on old phones. I use Next.js and Mantine UI for the site. I checked the site on other browsers such as Firefox and Opera - it works great for them, it doesn't freeze at all

**Comment by tunetheweb** [comment]
Doesn't sound like an issue for this library but a Chrome issue? Please raise an issue at https://crbug.com/new
