### ISSUE TITLE
LCP on user interaction?

### ISSUE THREAD

**Issue by skaraman** [GoogleChrome/web-vitals#60]
Why is LCP reported on user interaction?

I can load my page and sit on it for minutes before clicking, then LCP is reported for those minutes instead of when the actual content is shown.

**Comment by philipwalton** [comment]
It's a bit unclear which question you're asking:
- Why does this library wait until user interaction to report the value?
- Why does LCP (the metric itself) not consider images loaded after user interaction?

For the latter question, see this paragraph from [the LCP docs](https://web.dev/lcp/#when-is-largest-contentful-paint-reported):

> The browser will stop reporting new entries as soon as the user interacts with the page (via a tap, scroll, or keypress), as user interaction often changes what's visible to the user (which is especially true with scrolling).

For the former, the lib can't report the value until it knows no further LCP candidates might be loaded, so that's why it has to wait.

**Comment by skaraman** [comment]
<img width="646" alt="Screen Shot 2020-07-07 at 12 05 28 PM" src="https://user-images.githubusercontent.com/2840020/86833298-31943500-c04e-11ea-9783-d6b7c66fe316.png">
<img width="664" alt="Screen Shot 2020-07-07 at 12 34 58 PM" src="https://user-images.githubusercontent.com/2840020/86833364-4a044f80-c04e-11ea-9299-d7f3c7705188.png">
<img width="442" alt="Screen Shot 2020-07-07 at 12 36 44 PM" src="https://user-images.githubusercontent.com/2840020/86833583-918adb80-c04e-11ea-9a02-cf4f4e32dabf.png">


I'm using the implementation as shown in the readme `getLCP(console.log)` and this is what I see on my page. The first screenshot is me waiting ~2 seconds clicking, the second is waiting around ~10 seconds. getLCP returns the delta for the last entry which is my interaction. The chrome extension tool shows the same.

**Comment by philipwalton** [comment]
From your screenshot it looks like there's an additional entry in the `entries` array in the second example (6 vs 5), with a timestamp of 10207.58 ms. That makes me think your page is loading a new image at around 10 seconds into the page load.

Can you take a look at what element is referenced in that entry?

**Comment by skaraman** [comment]
Yes it looks like it's my 'hero' image, I think I found the issue, thank you! It appears to be related to a tabbed/scrolling hero image that is replaced with a new one after 10 seconds.

**Comment by skaraman** [comment]
@philipwalton Follow up question, since 'carousel' type header content is more or less common, is the solution to use a manual implementation of PerformanceObserver and splice out unwanted/needed entries from the carousel/auto-changing/scrolling behavior of the 'hero' image?
