### ISSUE TITLE
Cannot find CLS in Performance Tab

### ISSUE THREAD

**Issue by brndto** [GoogleChrome/web-vitals#64]
When I load the devtools on Chrome 86 when navigating to [CLS demo on JSBin](http://output.jsbin.com/zajamil) I can see the Layout Shift events under the Experience section but when I navigate to my site to find out what is causing it for me, I have no "Experience" section but the CLS icon constantly changes/flickers between red and green (Addy Osmani's web vitals extension).

Sorry if this is the wrong place for the issue.

**Comment by philipwalton** [comment]
You should probably file a Chrome DevTools issue at [crbug.com](https://crbug.com). These issues are just for the JavaScript library in this repo, not for general  Web Vitals-related questions.
