### ISSUE TITLE
Serve from gstatic.com or googleusercontent.com?

### ISSUE THREAD

**Issue by vsekhar** [GoogleChrome/web-vitals#66]

**Comment by paulirish** [comment]
https://github.com/GoogleChrome/web-vitals#load-web-vitals-from-a-cdn covers typical CDN usage. 

hypothetically we could add w-v.js to the [Hosted Libraries CDN](https://developers.google.com/speed/libraries) but it's more performant for this lib to be served along with 1st party code.

**Comment by vsekhar** [comment]
Is it moer performant because there is already a connection open to the 1st party, or for some other reason?

I'm specifically thinking about serving it alongside gtag.

**Comment by paulirish** [comment]
> Is it more performant because there is already a connection open to the 1st party

well.. if it remained a standalong file, then the difference is overhead of creating a connection to a new host. 

but if its 1P, then it'd likely be served as part of an existing bundle, which would make it significantly faster than as a standalone network resource.

**Comment by vsekhar** [comment]
I guess that's a question for gtag. Bundling makes sense.

Resolving for now.
