### ISSUE TITLE
Possible to use "standalone" in Chrome headless?

### ISSUE THREAD

**Issue by Joshfindit** [GoogleChrome/web-vitals#70]
"Standalone" as in: site does not install web-vitals

**Comment by sj5505** [comment]
> ### 

- 

- [ ] _**@``**_

**Comment by meikidd** [comment]
Hi @Joshfindit , I think you can achieve it by using puppeteer. 

[page.addStyleTag()](https://github.com/puppeteer/puppeteer/blob/v5.2.1/docs/api.md#pageaddscripttagoptions) function might be helpful.

**Comment by Joshfindit** [comment]
For future searchers who may be thinking the same way I am (automate the testing and integrate it in to a tool): Pagespeed Insights includes (most of) the Core Web Vitals (First Contentful Paint instead of LCP), and does have an API.
https://developers.google.com/speed/docs/insights/v5/get-started

**Comment by philipwalton** [comment]
To answer the direct question: yes, it is definitely possible to add the `web-vitals` library to a site and run it in headless Chrome, just as you'd add any script to a site in headless Chrome (via something like puppeteer).

However, the primary point of this library is for Real User Monitoring (RUM). If you want to measure performance in the lab, I'd recommend Lighthouse or Web Page Test.
