### ISSUE TITLE
FCP is larger than LCP

### ISSUE THREAD

**Issue by meikidd** [GoogleChrome/web-vitals#71]
Thanks for this awesome library. 

I am using GA for collecting the web vitals data. From GA dashboard, I can see FCP value is larger than LCP at some date, which is beyond our expectation(FCP should be less than LCP). Seems there is something wrong.

![image](https://user-images.githubusercontent.com/376338/89124284-52925d80-d508-11ea-849e-5e13b9901587.png)

I am using web-vitals v0.2.2.

The following is my data reporting code (pls let me know if I am using it incorrectly):

```
import {getFCP, getLCP} from 'web-vitals';

function sendToGoogleAnalytics({name, delta, id}) {
  // Assumes the global `gtag()` function exists, see:
  // https://developers.google.com/analytics/devguides/collection/gtagjs
  gtag('event', name, {
    event_category: 'Web Vitals',
    // Google Analytics metrics must be integers, so the value is rounded.
    // For CLS the value is first multiplied by 1000 for greater precision
    // (note: increase the multiplier for greater precision if needed).
    value: Math.round(name === 'CLS' ? delta * 1000 : delta),
    // The `id` value will be unique to the current page load. When sending
    // multiple values from the same page (e.g. for CLS), Google Analytics can
    // compute a total by grouping on this ID (note: requires `eventLabel` to
    // be a dimension in your report).
    event_label: id,
    // Use a non-interaction event to avoid affecting bounce rate.
    non_interaction: true,
  });
}

getFCP(sendToGoogleAnalytics);
getLCP(sendToGoogleAnalytics);
```

**Comment by bripkens** [comment]
You are most likely experiencing what our customers are experiencing as well with real-user data: https://www.instana.com/docs/website_monitoring/faq#why-are-some-website-metrics-not-always-available-andor-have-weird-values

Excerpt:

> This in turn can mean that statistical aggregations across a set of observations result in smaller LCP than FCP values. While this is impossible to observe for a single page load, it can occur for a set of page loads given a difference in web browser support as the following examples shows.
> Observed First-Contentful Paint values: 1000 ms, 1400 ms, 1600 ms. Mean: 1333ms.
> Observed Largest-Contentful Paint values: 1000 ms, UNSUPPORTED METRIC, 1600 ms. Mean: 1300ms.

**Comment by meikidd** [comment]
I tried to add a filter "browser == Chrome", and then there is no more FCP > LCP. 

@bripkens Thank you for your explanation.
