### ISSUE TITLE
Visually Complete 

### ISSUE THREAD

**Issue by rpellette** [GoogleChrome/web-vitals#73]
Many developers and SREs use custom versions of "visually complete", but every implementation has problems. For example, client side javascript is limited and often inaccurate, extension-based screenshots are inefficient, etc. 

It is a challenging problem to solve since sites vary with dynamic content such as carousels, moving ads, and user interaction, but it would help a lot to have some measurement indicating most above the fold rendering has finished. Any dynamic content after that could be ignored and any user interaction could null the measurement. 

Please consider adding this as a standard measurement to web vitals. Ideally a version of this can become a standard available in the performance api.

**Comment by philipwalton** [comment]
Thanks for the suggestion. For context, though, this library is not a generic performance tracking library. It only aims to enable measurement of [Web Vitals metrics that are field-measurable](https://github.com/GoogleChrome/web-vitals#overview). In other words, unless some sort of "visually complete" metric becomes officially part of the Web Vitals initiate at Google, and unless there's a Web API that makes it measurable in the field, then it won't make sense to add it to this library.

If you feel strongly that a "visually complete" metric would be useful, you can suggest that at [web-vitals-feedback@googlegroups.com](https://groups.google.com/g/web-vitals-feedback). However, my understanding is a visually complete metric has been explored in the past and it wasn't particularly accurate or useful. That is, lots of sites are never "visually complete", and the metric you care about isn't when the site is "complete" but rather then it's "ready", and LCP is currently the best metric we have to measure that.
