### ISSUE TITLE
The isFinal flag is confusing

### ISSUE THREAD

**Issue by philipwalton** [GoogleChrome/web-vitals#82]
The initial intent of the `isFinal` flag was allow consumers of this library to know when LCP was finalized (since the [Largest Contentful Paint API](https://wicg.github.io/largest-contentful-paint/) does not currently expose this information). However, given #75, the heuristics will become significantly less accurate if we're not tracking scrolls.

The `isFinal` flag was also a bit weird because it only really applied to LCP. CLS is not final until the page has unloaded, and FCP, FID, and TTFB are always final after the first entry is dispatched.

I've also seen examples in the wild where developers were misunderstanding `isFinal` and waiting until it was `true` before sending the data to their analytics provider. That is definitely *not* what `isFinal` is for, and something needs to be done to avoid that confusion.

**Comment by kkdev163** [comment]
> I've also seen examples in the wild where developers were misunderstanding isFinal and waiting until it was true before sending the data to their analytics provider. 

Actually, i'm using in this way.   In our monitor SDK, we have tried to  listen to unload event then use sendBeacon api to send vitals data, but we find it is not reliable..

So we wait for the LCP final , as the signal to send vitals data, it will help us collect more user's vitals data.

**Comment by philipwalton** [comment]
> Actually, i'm using in this way. In our monitor SDK, we have tried to listen to unload event then use sendBeacon api to send vitals data, but we find it is not reliable..

It is not reliable, and it is bad for performance. Do not wait for the `unload` event (see explanations below):

- https://web.dev/bfcache/#never-use-the-unload-event
- https://developers.google.com/web/updates/2018/07/page-lifecycle-api#the-unload-event
- https://github.com/mdn/sprints/issues/3722#issuecomment-699529808

> So we wait for the LCP final , seen it as the signal to send vitals data, it will help us collect more user's vitals data.

In v1, you will not be able to do this. My recommendation is to send the data when the callback fires. The callback will fire at the ideal moment for sending the data, for each metric.

If you want to aggregate the metrics and send it in a single request, then you'll have to do that yourself or use a library like [web-vitals-reporter](https://github.com/treosh/web-vitals-reporter) (which I recommend, as it handles this use case very well).

If you want to do it yourself, then I'd recommend sending the data in the `visibilitychange` event, similar to [how the `web-vitals-reporter` library does it](https://github.com/treosh/web-vitals-reporter/blob/72a807e1df5749896668665d1d28867902ae909d/src/index.js#L66-L86).

**Comment by kkdev163** [comment]
> If you want to do it yourself, then I'd recommend sending the data in the visibilitychange event, similar to how the web-vitals-reporter library does it.

Nice, thanks for your actionable advice, we will dive in to this libaray.
