### ISSUE TITLE
Typescript - Could not find a declaration file for module 'web-vitals'

### ISSUE THREAD

**Issue by magicaltrip** [GoogleChrome/web-vitals#89]
## What is happening

With the new version of `web-vitals@1.0.0`, typescript cannot find a declaration file for the module.

## How to reproduce

https://github.com/magicaltrip/webvitals-issue

Thanks

**Comment by philipwalton** [comment]
Sorry! This should be fixed in `v1.0.1`. Let me know if you're still seeing issues.
