### ISSUE TITLE
Extend metrics

### ISSUE THREAD

**Issue by pan-alexey** [GoogleChrome/web-vitals#93]
Additional metrics that can be useful for analysis:
`LTC - long tasks counts`
`TCPT (tcp time) = perfomance.timing.connectEnd - perfomance.timing.connectStart;`
`RedirectTime = perfomance.timing.redirectStart - perfomance.timing.redirectEnd;`
`redirectCount = navigation.redirectCount`

**Comment by philipwalton** [comment]
Thanks for the suggestions, but I don't think it makes sense to add these metrics for the same reasons I outlined in https://github.com/GoogleChrome/web-vitals/pull/92#issuecomment-731412738. These can already by measuring using the Navigation Timing API, which is exposed via TTFB.

**Comment by pan-alexey** [comment]
Ok. And how i can get LTC?

**Comment by philipwalton** [comment]
You could do something like this:

```js
import {getTTFB} from 'web-vitals';

getTTFB((metric) => {
  const timeToLastByte = metric.entries[0].requestEnd;
  console.log('Time to last byte:', timeToLastByte);
});
```

**Comment by pan-alexey** [comment]
Thank you very much @philipwalton  for your reply.
