### ISSUE TITLE
Frames per second (FPS) ?

### ISSUE THREAD

**Issue by tedpennings** [GoogleChrome/web-vitals#96]
Hello all,

Would all you be open to a PR to add an FPS meter? 

It could be something simple as this: for each timestamp argument to `window.requestAnimationFrame`, round down by 1000, and count how many are within the same second. It would also need to watch for 0 FPS gaps over a certain reporting interval (5s? 10s?). I have code I could contribute.

How would something like that fit within the architecture of this package? -- `getFPS()` ?

**Comment by philipwalton** [comment]
Thanks for the suggestion, but the intention of this library is to be an implementation of the metrics documented on [web.dev/vitals](https://web.dev/vitals/), so unless an FPS metric is added as an official "Web Vitals" metric, then I do not want to include it in this library.

We have discussed the possibility of adding some sort of "animation smoothness" metric to Web Vitals, but before we do that we'd want to also spec an API that can be measured with `PerformanceObserver`. Adding a never-ending `requestAnimationFrame()` loop to a page would probably work, but it would have the negative side-effect of using more CPU than necessary, which is bad for battery life on mobile.
