### ISSUE TITLE
Difference in LCP measurements in web-vitals library and Lighthouse (No throttling)

### ISSUE THREAD

**Issue by AnchalGupta3** [GoogleChrome/web-vitals#98]
<img width="1440" alt="Screenshot 2020-11-23 at 3 19 56 PM" src="https://user-images.githubusercontent.com/70004243/99948530-9e129500-2d9f-11eb-8eb7-409ce121f627.png">
<img width="1440" alt="Screenshot 2020-11-23 at 3 20 16 PM" src="https://user-images.githubusercontent.com/70004243/99948563-a8349380-2d9f-11eb-80b7-d6d8b1e21316.png">

I had implemented the web-vitals library in the website and ran lighthouse from dev tools. As shown in the screenshots, for the same run, web-vitals library is reporting LCP at 4.2s, whereas Lighthouse is reporting LCP at 7.9s. Could you please tell me, why am I getting different results in the same run?

**Comment by Zizzamia** [comment]
Ciao @AnchalGupta3, the key of the answer is that you are comparing 🍊 with 🍏. One is a Lab Data and the other is Field Data. Even if at the core might seems the same, the logic and heuristic behind those two are different and they should never be compared. Use the Lab Data to prevent quick regression before deploying in Prod, or better understand opportunity Lighthouse will advice to address, and use Field Data with a large set of users to see how your product will perform differently with different device, network and platforms.

**Comment by philipwalton** [comment]
@AnchalGupta3 is this still an issue? I would expect the numbers to be the same for the same run, so presumably this was a bug that has been fixed?
